// Bengali Common Phrases — 12 situational categories, ~144 phrases total
// Format follows grammar.js pattern for consistency.

// ════════════════════════════════════════
//  SITUATIONS (metadata for each category)
// ════════════════════════════════════════
const PHRASES_SITUATIONS = [
  { slug: "greetings", title: "Greetings & Farewells", icon: "👋", desc: "Say hello, goodbye, and ask how someone is doing" },
  { slug: "politeness", title: "Politeness & Requests", icon: "🙏", desc: "Please, thank you, sorry, and polite expressions" },
  { slug: "questions", title: "Asking Questions", icon: "❓", desc: "Question words and how to ask for help" },
  { slug: "introductions", title: "Introductions", icon: "🤝", desc: "Introduce yourself and learn about others" },
  { slug: "food", title: "At a Restaurant", icon: "🍛", desc: "Order food, ask about dishes, and pay the bill" },
  { slug: "transport", title: "Transport", icon: "🚌", desc: "Take buses, rickshaws, trains, and taxis" },
  { slug: "directions", title: "Directions & Places", icon: "🗺️", desc: "Ask for and give directions around town" },
  { slug: "shopping", title: "Shopping & Bargaining", icon: "🛍️", desc: "Buy things, ask about prices, and bargain" },
  { slug: "time", title: "Time & Scheduling", icon: "🕐", desc: "Talk about time, dates, and making plans" },
  { slug: "health", title: "Health & Emergencies", icon: "🏥", desc: "Describe symptoms and get help in emergencies" },
  { slug: "social", title: "Social Conversation", icon: "💬", desc: "Small talk, opinions, and social expressions" },
  { slug: "numbers", title: "Numbers in Context", icon: "🔢", desc: "Count, give prices, ages, and phone numbers" },
];

// Wave unlock order — earlier situations unlock first.
// Each situation unlocks when 60% of the previous situation's phrases reach mastery ≥ 2.
const PHRASES_WAVE_ORDER = [
  "greetings",
  "politeness",
  "questions",
  "introductions",
  "food",
  "transport",
  "directions",
  "shopping",
  "time",
  "health",
  "social",
  "numbers",
];

// ════════════════════════════════════════
//  PHRASE DATA
// ════════════════════════════════════════
// Schema:
//   id        – unique kebab-case identifier (used as mastery key)
//   situation – slug matching PHRASES_SITUATIONS
//   bengali   – Bengali script
//   roman     – romanized pronunciation
//   english   – English translation (with register note if needed)
//   notes     – optional cultural/grammatical note
//   reply     – optional { bengali, roman, english } natural response phrase

const PHRASES_DATA = [
  // ═══════════════════════════════════════
  //  GREETINGS & FAREWELLS  (12 phrases)
  // ═══════════════════════════════════════
  {
    id: "greet-salam",
    situation: "greetings",
    bengali: "আস্সালামু আলাইকুম",
    roman: "as-salamu alaikum",
    english: "Peace be upon you (Islamic greeting)",
    notes: "The standard Muslim greeting in Bangladesh. Always appropriate in any formal or social setting.",
    reply: { bengali: "ওয়া আলাইকুম আস-সালাম", roman: "wa alaikum as-salam", english: "And upon you peace" },
  },
  {
    id: "greet-nomoshkar",
    situation: "greetings",
    bengali: "নমস্কার",
    roman: "nomoshkar",
    english: "Hello / Greetings (Hindu or secular greeting)",
    notes: "Common in West Bengal and among Hindus. Also used as a general secular greeting.",
    reply: { bengali: "নমস্কার", roman: "nomoshkar", english: "Hello (in return)" },
  },
  {
    id: "greet-kemon-achen",
    situation: "greetings",
    bengali: "আপনি কেমন আছেন?",
    roman: "apni kemon achen?",
    english: "How are you? (formal)",
    notes: 'আপনি is the formal "you". Use this with strangers, elders, and in professional settings.',
    reply: { bengali: "ভালো আছি, ধন্যবাদ। আপনি?", roman: "bhalo achi, dhonnobad. apni?", english: "I'm well, thank you. And you?" },
  },
  {
    id: "greet-kemon-acho",
    situation: "greetings",
    bengali: "তুমি কেমন আছ?",
    roman: "tumi kemon acho?",
    english: "How are you? (informal)",
    notes: "তুমি is for friends, peers, and people younger than you.",
    reply: { bengali: "ভালো আছি, তুমি?", roman: "bhalo achi, tumi?", english: "I'm fine, and you?" },
  },
  {
    id: "greet-shubho-shokal",
    situation: "greetings",
    bengali: "শুভ সকাল",
    roman: "shubho shokal",
    english: "Good morning",
  },
  {
    id: "greet-shubho-bikel",
    situation: "greetings",
    bengali: "শুভ বিকেল",
    roman: "shubho bikel",
    english: "Good afternoon",
  },
  {
    id: "greet-shubho-shondhya",
    situation: "greetings",
    bengali: "শুভ সন্ধ্যা",
    roman: "shubho shondhya",
    english: "Good evening",
  },
  {
    id: "greet-shubho-ratri",
    situation: "greetings",
    bengali: "শুভ রাত্রি",
    roman: "shubho ratri",
    english: "Good night",
  },
  {
    id: "greet-biday",
    situation: "greetings",
    bengali: "বিদায়",
    roman: "biday",
    english: "Goodbye (formal)",
    notes: "More formal than আসি. Often used in written communication or formal speech.",
  },
  {
    id: "greet-ashi",
    situation: "greetings",
    bengali: "আসি",
    roman: "ashi",
    english: 'See you / Goodbye (casual, lit. "I\'m going")',
    notes: "The everyday casual goodbye. More natural than বিদায় in spoken conversation.",
  },
  {
    id: "greet-abar-dekha",
    situation: "greetings",
    bengali: "আবার দেখা হবে",
    roman: "abar dekha hobe",
    english: "See you again",
  },
  {
    id: "greet-bhalo-thakben",
    situation: "greetings",
    bengali: "ভালো থাকবেন",
    roman: "bhalo thakben",
    english: "Take care / Stay well (formal parting)",
    notes: "A warm, respectful way to say goodbye, often used with elders or in formal contexts.",
  },

  // ═══════════════════════════════════════
  //  POLITENESS & REQUESTS  (12 phrases)
  // ═══════════════════════════════════════
  {
    id: "pol-please",
    situation: "politeness",
    bengali: "দয়া করে",
    roman: "doya kore",
    english: 'Please (lit. "with kindness")',
    notes: "Placed before the verb or request. Can also be placed at the end of a sentence.",
  },
  {
    id: "pol-thankyou",
    situation: "politeness",
    bengali: "ধন্যবাদ",
    roman: "dhonnobad",
    english: "Thank you",
  },
  {
    id: "pol-thankyou-much",
    situation: "politeness",
    bengali: "অনেক ধন্যবাদ",
    roman: "onek dhonnobad",
    english: "Thank you very much",
  },
  {
    id: "pol-welcome",
    situation: "politeness",
    bengali: "আপনাকে স্বাগতম",
    roman: "apnake shagotom",
    english: "You're welcome / Welcome",
    notes: 'Also used to greet guests or visitors. As a response to thanks, you can also say "কোনো ব্যাপার না" (no problem).',
  },
  {
    id: "pol-excuseme",
    situation: "politeness",
    bengali: "মাফ করবেন",
    roman: "maph korben",
    english: "Excuse me / Pardon me (formal)",
    notes: "Use to get someone's attention or to apologize for a minor inconvenience.",
  },
  {
    id: "pol-sorry",
    situation: "politeness",
    bengali: "দুঃখিত",
    roman: "dukhkhito",
    english: "I'm sorry / I apologize",
    notes: "A sincere apology. For lighter situations, মাফ করবেন is more common.",
  },
  {
    id: "pol-okay",
    situation: "politeness",
    bengali: "ঠিক আছে",
    roman: "thik ache",
    english: "Okay / Alright / That's fine",
    notes: "One of the most versatile phrases. Can express agreement, acceptance, or acknowledgment.",
  },
  {
    id: "pol-yes",
    situation: "politeness",
    bengali: "হ্যাঁ",
    roman: "hya",
    english: "Yes",
  },
  {
    id: "pol-no",
    situation: "politeness",
    bengali: "না",
    roman: "na",
    english: "No",
  },
  {
    id: "pol-wait",
    situation: "politeness",
    bengali: "একটু অপেক্ষা করুন",
    roman: "ektu opekha korun",
    english: "Please wait a moment",
  },
  {
    id: "pol-didnt-understand",
    situation: "politeness",
    bengali: "আমি বুঝতে পারিনি",
    roman: "ami bujhte parini",
    english: "I didn't understand",
    notes: "Essential phrase for learners! Follow with একটু ধীরে বলবেন? (can you speak more slowly?).",
  },
  {
    id: "pol-slowly",
    situation: "politeness",
    bengali: "একটু ধীরে বলবেন?",
    roman: "ektu dhire bolben?",
    english: "Could you speak a little more slowly?",
  },

  // ═══════════════════════════════════════
  //  ASKING QUESTIONS  (12 phrases)
  // ═══════════════════════════════════════
  {
    id: "quest-what-this",
    situation: "questions",
    bengali: "এটা কী?",
    roman: "eta ki?",
    english: "What is this?",
  },
  {
    id: "quest-what-that",
    situation: "questions",
    bengali: "ওটা কী?",
    roman: "ota ki?",
    english: "What is that?",
    notes: "এটা = this (near), ওটা = that (far away).",
  },
  {
    id: "quest-where",
    situation: "questions",
    bengali: "কোথায়?",
    roman: "kothay?",
    english: "Where?",
  },
  {
    id: "quest-when",
    situation: "questions",
    bengali: "কখন?",
    roman: "kokhon?",
    english: "When?",
  },
  {
    id: "quest-why",
    situation: "questions",
    bengali: "কেন?",
    roman: "keno?",
    english: "Why?",
  },
  {
    id: "quest-how",
    situation: "questions",
    bengali: "কিভাবে?",
    roman: "kibhabe?",
    english: "How?",
  },
  {
    id: "quest-how-much",
    situation: "questions",
    bengali: "কত?",
    roman: "koto?",
    english: "How much? / How many?",
  },
  {
    id: "quest-who",
    situation: "questions",
    bengali: "কে?",
    roman: "ke?",
    english: "Who?",
  },
  {
    id: "quest-english",
    situation: "questions",
    bengali: "আপনি কি ইংরেজি বলতে পারেন?",
    roman: "apni ki ingreji bolte paren?",
    english: "Can you speak English?",
    reply: { bengali: "একটু পারি।", roman: "ektu pari.", english: "A little." },
  },
  {
    id: "quest-say-bengali",
    situation: "questions",
    bengali: "এটা বাংলায় কী বলে?",
    roman: "eta banglay ki bole?",
    english: "How do you say this in Bengali?",
  },
  {
    id: "quest-write-down",
    situation: "questions",
    bengali: "এটা কি লিখে দেবেন?",
    roman: "eta ki likhe deben?",
    english: "Could you write that down?",
  },
  {
    id: "quest-lost",
    situation: "questions",
    bengali: "আমি হারিয়ে গেছি",
    roman: "ami hariye gechi",
    english: "I'm lost",
  },

  // ═══════════════════════════════════════
  //  INTRODUCTIONS  (12 phrases)
  // ═══════════════════════════════════════
  {
    id: "intro-my-name",
    situation: "introductions",
    bengali: "আমার নাম...",
    roman: "amar nam...",
    english: "My name is...",
  },
  {
    id: "intro-your-name-formal",
    situation: "introductions",
    bengali: "আপনার নাম কী?",
    roman: "apnar nam ki?",
    english: "What is your name? (formal)",
    reply: { bengali: "আমার নাম...", roman: "amar nam...", english: "My name is..." },
  },
  {
    id: "intro-nice-to-meet",
    situation: "introductions",
    bengali: "আপনার সাথে পরিচিত হয়ে ভালো লাগলো",
    roman: "apnar shathe porichit hoye bhalo laglo",
    english: "Nice to meet you",
    reply: { bengali: "আমারও", roman: "amaro", english: "Same here / Me too" },
  },
  {
    id: "intro-from",
    situation: "introductions",
    bengali: "আমি [দেশ] থেকে এসেছি",
    roman: "ami [desh] theke eshechi",
    english: "I'm from [country]",
    notes: "Replace [দেশ] with your country: আমেরিকা (America), ইংল্যান্ড (England), ভারত (India), ইত্যাদি.",
  },
  {
    id: "intro-where-from",
    situation: "introductions",
    bengali: "আপনি কোথা থেকে এসেছেন?",
    roman: "apni kotha theke eshechen?",
    english: "Where are you from? (formal)",
  },
  {
    id: "intro-what-do-you-do",
    situation: "introductions",
    bengali: "আপনি কী করেন?",
    roman: "apni ki koren?",
    english: "What do you do? (formal)",
  },
  {
    id: "intro-i-am-a",
    situation: "introductions",
    bengali: "আমি একজন শিক্ষার্থী",
    roman: "ami ekjon shikkharthi",
    english: "I am a student",
    notes: "Replace শিক্ষার্থী with your profession: শিক্ষক (teacher), ডাক্তার (doctor), প্রকৌশলী (engineer).",
  },
  {
    id: "intro-learning-bengali",
    situation: "introductions",
    bengali: "আমি বাংলা শিখছি",
    roman: "ami bangla shikhchi",
    english: "I'm learning Bengali",
    notes: "A phrase that will delight any Bengali speaker! You'll likely get a warm response.",
  },
  {
    id: "intro-how-old",
    situation: "introductions",
    bengali: "আপনার বয়স কত?",
    roman: "apnar boyosh koto?",
    english: "How old are you? (formal)",
    notes: "In Bengali culture, asking someone's age is generally polite, not intrusive.",
  },
  {
    id: "intro-my-age",
    situation: "introductions",
    bengali: "আমার বয়স... বছর",
    roman: "amar boyosh... bochhor",
    english: "I am ... years old",
  },
  {
    id: "intro-married",
    situation: "introductions",
    bengali: "আপনি কি বিবাহিত?",
    roman: "apni ki bibahit?",
    english: "Are you married?",
    notes: "A common conversation topic in Bengali culture, not considered intrusive.",
  },
  {
    id: "intro-i-love-bengali",
    situation: "introductions",
    bengali: "আমি বাংলাদেশ ভালোবাসি",
    roman: "ami Bangladesh bhalobashi",
    english: "I love Bangladesh",
    notes: "Change বাংলাদেশ to বাংলা (the language/culture) or পশ্চিমবঙ্গ (West Bengal) as appropriate.",
  },

  // ═══════════════════════════════════════
  //  AT A RESTAURANT  (12 phrases)
  // ═══════════════════════════════════════
  {
    id: "food-menu",
    situation: "food",
    bengali: "মেনু দেখাবেন?",
    roman: "menu dekhaben?",
    english: "Could I see the menu?",
  },
  {
    id: "food-order",
    situation: "food",
    bengali: "আমি [খাবার] খেতে চাই",
    roman: "ami [khabar] khete chai",
    english: "I would like to eat [food]",
    notes: "Replace [খাবার] with the dish: ভাত (rice), মাছ (fish), মুরগি (chicken), ডাল (lentils).",
  },
  {
    id: "food-bill",
    situation: "food",
    bengali: "বিলটা দিন",
    roman: "bilta din",
    english: "The bill, please",
  },
  {
    id: "food-spicy",
    situation: "food",
    bengali: "এটা কি ঝাল?",
    roman: "eta ki jhal?",
    english: "Is this spicy?",
    notes: "Bengali cuisine can be very spicy. Ask কম ঝাল করুন (make it less spicy) if needed.",
  },
  {
    id: "food-vegetarian",
    situation: "food",
    bengali: "আমি নিরামিষাশী",
    roman: "ami niramishashi",
    english: "I'm vegetarian",
    notes: "You can also say আমি মাংস খাই না (I don't eat meat).",
  },
  {
    id: "food-water",
    situation: "food",
    bengali: "পানি দিন",
    roman: "pani din",
    english: "Please give me water",
    notes: "পানি is used in Bangladesh; জল (jol) is used in West Bengal.",
  },
  {
    id: "food-halal",
    situation: "food",
    bengali: "এটা কি হালাল?",
    roman: "eta ki halal?",
    english: "Is this halal?",
    notes: "Most restaurants in Bangladesh serve halal food, but it's worth confirming in mixed areas.",
  },
  {
    id: "food-whats-in-it",
    situation: "food",
    bengali: "এতে কী কী আছে?",
    roman: "ete ki ki ache?",
    english: "What's in this (dish)?",
  },
  {
    id: "food-more",
    situation: "food",
    bengali: "আরেকটু দিন",
    roman: "arektu din",
    english: "Give me a little more, please",
  },
  {
    id: "food-delicious",
    situation: "food",
    bengali: "খুব সুস্বাদু",
    roman: "khub shushadu",
    english: "Very delicious",
    notes: "A great compliment to give after a meal. অনেক মজা হয়েছে (it was very tasty) also works.",
  },
  {
    id: "food-less-spicy",
    situation: "food",
    bengali: "কম ঝাল করুন",
    roman: "kom jhal korun",
    english: "Please make it less spicy",
  },
  {
    id: "food-no-allergies",
    situation: "food",
    bengali: "আমার [জিনিস]-এ অ্যালার্জি আছে",
    roman: "amar [jinish]-e allergy ache",
    english: "I'm allergic to [item]",
    notes: "Replace [জিনিস] with the allergen: বাদাম (nuts), দুধ (dairy), গম (wheat).",
  },

  // ═══════════════════════════════════════
  //  TRANSPORT  (12 phrases)
  // ═══════════════════════════════════════
  {
    id: "trans-go-to",
    situation: "transport",
    bengali: "আমি [জায়গা]-য় যেতে চাই",
    roman: "ami [jayga]-y jete chai",
    english: "I want to go to [place]",
    notes: "Replace [জায়গা] with the destination. Many place names in Bengali end with -তে or -য়.",
  },
  {
    id: "trans-fare",
    situation: "transport",
    bengali: "কত ভাড়া?",
    roman: "koto bhara?",
    english: "How much is the fare?",
  },
  {
    id: "trans-stop-here",
    situation: "transport",
    bengali: "এখানে থামুন",
    roman: "ekhane thamun",
    english: "Stop here, please",
  },
  {
    id: "trans-bus-leave",
    situation: "transport",
    bengali: "বাস কখন ছাড়বে?",
    roman: "bash kokhon chharbe?",
    english: "When does the bus leave?",
  },
  {
    id: "trans-ticket",
    situation: "transport",
    bengali: "টিকিট কোথায় পাব?",
    roman: "tikit kothay pabo?",
    english: "Where can I get a ticket?",
  },
  {
    id: "trans-which-bus",
    situation: "transport",
    bengali: "কোন বাসে যাব?",
    roman: "kon bashe jabo?",
    english: "Which bus should I take?",
  },
  {
    id: "trans-train-time",
    situation: "transport",
    bengali: "ট্রেন কি সময়মতো আছে?",
    roman: "train ki shomoy moto ache?",
    english: "Is the train on time?",
  },
  {
    id: "trans-rickshaw",
    situation: "transport",
    bengali: "রিকশায় কত লাগবে?",
    roman: "rikshay koto lagbe?",
    english: "How much by rickshaw?",
    notes: "Rickshaws are iconic in Dhaka and many other Bengali cities. Always negotiate the fare before getting in.",
  },
  {
    id: "trans-take-me",
    situation: "transport",
    bengali: "আমাকে এখানে নিয়ে যান",
    roman: "amake ekhane niey jan",
    english: "Take me here (showing address/location)",
  },
  {
    id: "trans-meter",
    situation: "transport",
    bengali: "মিটার চালু করুন",
    roman: "miṭar chalu korun",
    english: "Please start the meter",
    notes: "In Dhaka, CNGs (auto-rickshaws) have meters. Always insist on the meter or negotiate beforehand.",
  },
  {
    id: "trans-next-station",
    situation: "transport",
    bengali: "পরের স্টেশন কোনটা?",
    roman: "porer station konṭa?",
    english: "What is the next station?",
  },
  {
    id: "trans-bus-go",
    situation: "transport",
    bengali: "এই বাসটা কি ঢাকায় যায়?",
    roman: "ei bashṭa ki Dhakay jay?",
    english: "Does this bus go to Dhaka?",
    notes: "Replace ঢাকা with your destination.",
  },

  // ═══════════════════════════════════════
  //  DIRECTIONS & PLACES  (12 phrases)
  // ═══════════════════════════════════════
  {
    id: "dir-where-is",
    situation: "directions",
    bengali: "... কোথায়?",
    roman: "... kothay?",
    english: "Where is ...?",
    notes: "Add the place before কোথায়: হাসপাতাল কোথায়? (Where is the hospital?)",
  },
  {
    id: "dir-left",
    situation: "directions",
    bengali: "বাম দিকে যান",
    roman: "bam dike jan",
    english: "Turn left / Go left",
  },
  {
    id: "dir-right",
    situation: "directions",
    bengali: "ডান দিকে যান",
    roman: "dan dike jan",
    english: "Turn right / Go right",
  },
  {
    id: "dir-straight",
    situation: "directions",
    bengali: "সোজা যান",
    roman: "shoja jan",
    english: "Go straight",
  },
  {
    id: "dir-ahead",
    situation: "directions",
    bengali: "একটু সামনে",
    roman: "ektu shamne",
    english: "A little ahead / Just ahead",
  },
  {
    id: "dir-nearby",
    situation: "directions",
    bengali: "কাছেই আছে",
    roman: "kachheyi ache",
    english: "It's nearby / It's very close",
  },
  {
    id: "dir-far",
    situation: "directions",
    bengali: "অনেক দূরে",
    roman: "onek dure",
    english: "It's quite far",
  },
  {
    id: "dir-stop-here",
    situation: "directions",
    bengali: "এখানে নামব",
    roman: "ekhane nambo",
    english: "I'll get off here",
  },
  {
    id: "dir-corner",
    situation: "directions",
    bengali: "মোড়ে ঘুরুন",
    roman: "more ghurun",
    english: "Turn at the intersection",
  },
  {
    id: "dir-how-far",
    situation: "directions",
    bengali: "এটা কত দূর?",
    roman: "eta koto dur?",
    english: "How far is it?",
  },
  {
    id: "dir-show-way",
    situation: "directions",
    bengali: "আমাকে পথ দেখাতে পারবেন?",
    roman: "amake path dekhate parben?",
    english: "Could you show me the way?",
  },
  {
    id: "dir-on-this-road",
    situation: "directions",
    bengali: "এই রাস্তায় সোজা যান",
    roman: "ei rastay shoja jan",
    english: "Go straight on this road",
  },

  // ═══════════════════════════════════════
  //  SHOPPING & BARGAINING  (12 phrases)
  // ═══════════════════════════════════════
  {
    id: "shop-price",
    situation: "shopping",
    bengali: "এটার দাম কত?",
    roman: "etar dam koto?",
    english: "How much does this cost?",
  },
  {
    id: "shop-expensive",
    situation: "shopping",
    bengali: "অনেক দামি",
    roman: "onek dami",
    english: "Very expensive",
    notes: "Bargaining is expected at markets (বাজার). Start by expressing this and make a counter-offer.",
  },
  {
    id: "shop-reduce",
    situation: "shopping",
    bengali: "একটু কম করুন",
    roman: "ektu kom korun",
    english: "Please lower the price a bit",
  },
  {
    id: "shop-take-it",
    situation: "shopping",
    bengali: "আমি এটা নেব",
    roman: "ami eta nebo",
    english: "I'll take this",
  },
  {
    id: "shop-other-size",
    situation: "shopping",
    bengali: "অন্য সাইজ আছে?",
    roman: "onno shayij ache?",
    english: "Do you have another size?",
  },
  {
    id: "shop-other-color",
    situation: "shopping",
    bengali: "ভিন্ন রং আছে?",
    roman: "bhinno rong ache?",
    english: "Do you have a different color?",
  },
  {
    id: "shop-just-looking",
    situation: "shopping",
    bengali: "আমি শুধু দেখছি",
    roman: "ami shudhu dekhchi",
    english: "I'm just looking",
  },
  {
    id: "shop-genuine",
    situation: "shopping",
    bengali: "এটা কি আসল?",
    roman: "eta ki ashol?",
    english: "Is this genuine / authentic?",
  },
  {
    id: "shop-receipt",
    situation: "shopping",
    bengali: "রসিদ দিন",
    roman: "rishid din",
    english: "Please give me the receipt",
  },
  {
    id: "shop-card",
    situation: "shopping",
    bengali: "কার্ডে পেমেন্ট করা যাবে?",
    roman: "karde payment kora jabe?",
    english: "Can I pay by card?",
    notes: "Many smaller shops only accept cash (নগদ). ATMs are widely available in cities.",
  },
  {
    id: "shop-have-item",
    situation: "shopping",
    bengali: "আপনার কাছে কি এটা আছে?",
    roman: "apnar kache ki eta ache?",
    english: "Do you have this?",
  },
  {
    id: "shop-discount",
    situation: "shopping",
    bengali: "ছাড় দেওয়া যাবে?",
    roman: "chhar deowa jabe?",
    english: "Can you give me a discount?",
  },

  // ═══════════════════════════════════════
  //  TIME & SCHEDULING  (12 phrases)
  // ═══════════════════════════════════════
  {
    id: "time-what-time",
    situation: "time",
    bengali: "এখন কটা বাজে?",
    roman: "ekhon kota baje?",
    english: "What time is it now?",
    reply: { bengali: "এখন [সংখ্যা]টা বাজে", roman: "ekhon [shonkha]ta baje", english: "It is [number] o'clock now" },
  },
  {
    id: "time-what-date",
    situation: "time",
    bengali: "আজকে কত তারিখ?",
    roman: "ajke koto tarikh?",
    english: "What's today's date?",
  },
  {
    id: "time-today",
    situation: "time",
    bengali: "আজ",
    roman: "aj",
    english: "Today",
  },
  {
    id: "time-tomorrow",
    situation: "time",
    bengali: "আগামীকাল",
    roman: "agamikhal",
    english: "Tomorrow",
  },
  {
    id: "time-yesterday",
    situation: "time",
    bengali: "গতকাল",
    roman: "gotokhal",
    english: "Yesterday",
  },
  {
    id: "time-day-after",
    situation: "time",
    bengali: "পরশু",
    roman: "parshu",
    english: "The day after tomorrow",
  },
  {
    id: "time-late",
    situation: "time",
    bengali: "দেরি হয়ে গেছে",
    roman: "deri hoye geche",
    english: "It's gotten late / I'm running late",
  },
  {
    id: "time-when-meet",
    situation: "time",
    bengali: "কখন দেখা হবে?",
    roman: "kokhon dekha hobe?",
    english: "When will we meet?",
  },
  {
    id: "time-how-long",
    situation: "time",
    bengali: "কতক্ষণ লাগবে?",
    roman: "kotokhon lagbe?",
    english: "How long will it take?",
  },
  {
    id: "time-morning",
    situation: "time",
    bengali: "সকালে",
    roman: "shokale",
    english: "In the morning",
  },
  {
    id: "time-afternoon",
    situation: "time",
    bengali: "দুপুরে",
    roman: "dupure",
    english: "In the afternoon",
  },
  {
    id: "time-night",
    situation: "time",
    bengali: "রাতে",
    roman: "rate",
    english: "At night",
  },

  // ═══════════════════════════════════════
  //  HEALTH & EMERGENCIES  (12 phrases)
  // ═══════════════════════════════════════
  {
    id: "health-not-well",
    situation: "health",
    bengali: "আমার শরীর ভালো নেই",
    roman: "amar shorir bhalo nei",
    english: "I'm not feeling well",
  },
  {
    id: "health-need-doctor",
    situation: "health",
    bengali: "ডাক্তার দরকার",
    roman: "daktar dorkar",
    english: "I need a doctor",
  },
  {
    id: "health-hospital",
    situation: "health",
    bengali: "হাসপাতাল কোথায়?",
    roman: "hashpatal kothay?",
    english: "Where is the hospital?",
  },
  {
    id: "health-fever",
    situation: "health",
    bengali: "আমার জ্বর আছে",
    roman: "amar jor ache",
    english: "I have a fever",
  },
  {
    id: "health-stomach",
    situation: "health",
    bengali: "আমার পেটে ব্যথা",
    roman: "amar pete bytha",
    english: "I have a stomachache",
  },
  {
    id: "health-headache",
    situation: "health",
    bengali: "আমার মাথায় ব্যথা",
    roman: "amar mathay bytha",
    english: "I have a headache",
  },
  {
    id: "health-help",
    situation: "health",
    bengali: "সাহায্য করুন!",
    roman: "shahaijja korun!",
    english: "Help me! / Please help!",
    notes: "A critical emergency phrase. Shout loudly if in danger.",
  },
  {
    id: "health-police",
    situation: "health",
    bengali: "পুলিশ ডাকুন!",
    roman: "pulish dakun!",
    english: "Call the police!",
  },
  {
    id: "health-urgent",
    situation: "health",
    bengali: "এটা জরুরি!",
    roman: "eta joruri!",
    english: "This is urgent! / It's an emergency!",
  },
  {
    id: "health-pharmacy",
    situation: "health",
    bengali: "ওষুধের দোকান কোথায়?",
    roman: "oshudher dokan kothay?",
    english: "Where is the pharmacy?",
    notes: "Pharmacies are called ফার্মেসি (pharmacy) or ওষুধের দোকান (medicine shop) and are widely available.",
  },
  {
    id: "health-allergy",
    situation: "health",
    bengali: "আমার অ্যালার্জি আছে",
    roman: "amar allergy ache",
    english: "I have an allergy",
  },
  {
    id: "health-take-to-hospital",
    situation: "health",
    bengali: "আমাকে হাসপাতালে নিয়ে যান",
    roman: "amake hashpatale niey jan",
    english: "Take me to the hospital",
  },

  // ═══════════════════════════════════════
  //  SOCIAL CONVERSATION  (12 phrases)
  // ═══════════════════════════════════════
  {
    id: "soc-family-size",
    situation: "social",
    bengali: "আপনার পরিবারে কতজন?",
    roman: "apnar poribhare kotojohn?",
    english: "How many people are in your family?",
  },
  {
    id: "soc-where-live",
    situation: "social",
    bengali: "আপনি কোথায় থাকেন?",
    roman: "apni kothay thaken?",
    english: "Where do you live? (formal)",
  },
  {
    id: "soc-like-food",
    situation: "social",
    bengali: "আমার বাংলা খাবার পছন্দ",
    roman: "amar bangla khabar poshond",
    english: "I like Bengali food",
  },
  {
    id: "soc-beautiful-country",
    situation: "social",
    bengali: "আপনার দেশ খুব সুন্দর",
    roman: "apnar desh khub shundor",
    english: "Your country is very beautiful",
  },
  {
    id: "soc-come-again",
    situation: "social",
    bengali: "আমি আবার আসতে চাই",
    roman: "ami abar ashte chai",
    english: "I want to come back again",
  },
  {
    id: "soc-lets-go",
    situation: "social",
    bengali: "চলুন একসাথে যাই",
    roman: "cholun ek shathe jai",
    english: "Let's go together",
  },
  {
    id: "soc-like-movies",
    situation: "social",
    bengali: "আপনি কি সিনেমা পছন্দ করেন?",
    roman: "apni ki shinama poshond koren?",
    english: "Do you like movies? (formal)",
  },
  {
    id: "soc-enjoyed-talking",
    situation: "social",
    bengali: "আপনার সাথে কথা বলে ভালো লাগলো",
    roman: "apnar shathe kotha bole bhalo laglo",
    english: "I enjoyed talking with you",
  },
  {
    id: "soc-best-wishes",
    situation: "social",
    bengali: "শুভকামনা",
    roman: "shubhokamona",
    english: "Best wishes",
  },
  {
    id: "soc-wish-success",
    situation: "social",
    bengali: "আপনার সাফল্য কামনা করি",
    roman: "apnar shafolya kamona kori",
    english: "I wish you success",
  },
  {
    id: "soc-been-to-bangladesh",
    situation: "social",
    bengali: "আপনি কি কখনো বাংলাদেশে গেছেন?",
    roman: "apni ki kokhono Bangladeshe gechen?",
    english: "Have you ever been to Bangladesh?",
  },
  {
    id: "soc-places-to-visit",
    situation: "social",
    bengali: "বাংলাদেশে কোথায় যাওয়া ভালো?",
    roman: "Bangladeshe kothay jaowa bhalo?",
    english: "What are good places to visit in Bangladesh?",
  },

  // ═══════════════════════════════════════
  //  NUMBERS IN CONTEXT  (12 phrases)
  // ═══════════════════════════════════════
  {
    id: "num-1-3",
    situation: "numbers",
    bengali: "এক, দুই, তিন",
    roman: "ek, dui, tin",
    english: "One, two, three",
  },
  {
    id: "num-4-6",
    situation: "numbers",
    bengali: "চার, পাঁচ, ছয়",
    roman: "char, pach, chhoy",
    english: "Four, five, six",
  },
  {
    id: "num-7-10",
    situation: "numbers",
    bengali: "সাত, আট, নয়, দশ",
    roman: "shat, at, noy, dosh",
    english: "Seven, eight, nine, ten",
  },
  {
    id: "num-11-13",
    situation: "numbers",
    bengali: "এগারো, বারো, তেরো",
    roman: "egaro, baro, tero",
    english: "Eleven, twelve, thirteen",
  },
  {
    id: "num-20-40",
    situation: "numbers",
    bengali: "বিশ, ত্রিশ, চল্লিশ",
    roman: "bish, trish, challish",
    english: "Twenty, thirty, forty",
  },
  {
    id: "num-50-70",
    situation: "numbers",
    bengali: "পঞ্চাশ, ষাট, সত্তর",
    roman: "ponchash, shat, sottor",
    english: "Fifty, sixty, seventy",
  },
  {
    id: "num-80-100",
    situation: "numbers",
    bengali: "আশি, নব্বই, একশো",
    roman: "ashi, nobboi, ekho",
    english: "Eighty, ninety, one hundred",
  },
  {
    id: "num-thousand",
    situation: "numbers",
    bengali: "এক হাজার",
    roman: "ek hajar",
    english: "One thousand",
  },
  {
    id: "num-phone",
    situation: "numbers",
    bengali: "আমার ফোন নম্বর হলো...",
    roman: "amar phone nombor holo...",
    english: "My phone number is...",
  },
  {
    id: "num-price",
    situation: "numbers",
    bengali: "এটা... টাকা",
    roman: "eta... taka",
    english: "This costs ... taka",
    notes: "টাকা (taka) is the currency of Bangladesh. In India, rupee is রুপি (rupee).",
  },
  {
    id: "num-ordinals",
    situation: "numbers",
    bengali: "প্রথম, দ্বিতীয়, তৃতীয়",
    roman: "prothom, dwitiyo, tritiyo",
    english: "First, second, third",
  },
  {
    id: "num-half-double",
    situation: "numbers",
    bengali: "অর্ধেক, দ্বিগুণ",
    roman: "ordhek, dwiguno",
    english: "Half, double",
  },
];

export { PHRASES_SITUATIONS, PHRASES_WAVE_ORDER, PHRASES_DATA };
