// Bengali Vocabulary — 1000 most common words
// Format: [bengali, romanized, english, category, partOfSpeech]

// TODO: Add example sentences as the 6th element of each word entry.
// Format: ["bengali", "roman", "english", "category", "pos", "example sentence in Bengali (optional romanization)"]
// Example: ["আমি","ami","I / me","pronouns","pronoun","আমি বাংলা শিখছি। (ami bangla shikhchi — I am learning Bengali.)"],
//
// Once added, update showVocabDetail() and the vocab flashcard back face in index.html
// to render w[5] as an example sentence row.

const VOCAB_DATA = [
// ─── PRONOUNS & DEMONSTRATIVES (25) ───
["আমি","ami","I / me","pronouns","pronoun","আমি বাংলা শিখছি। (ami bangla shikhchhi — I am learning Bengali.)"],
["তুমি","tumi","you (informal)","pronouns","pronoun","তুমি কোথায় যাচ্ছ? (tumi kothay jaccho — Where are you going?)"],
["আপনি","apni","you (formal)","pronouns","pronoun","আপনি কি ঢাকায় থাকেন? (apni ki dhakay thaken — Do you live in Dhaka?)"],
["তুই","tui","you (very informal)","pronouns","pronoun","তুই আমার বন্ধু। (tui amar bondhu — You are my friend.)"],
["সে","she","he / she / they (singular)","pronouns","pronoun","সে আমাদের শিক্ষক। (she amader shikkhok — He/she is our teacher.)"],
["তিনি","tini","he / she (formal)","pronouns","pronoun","তিনি খুব ভালো মানুষ। (tini khub bhalo manush — He/she is a very good person.)"],
["আমরা","amra","we","pronouns","pronoun","আমরা একসাথে যাব। (amra ekshate jabo — We will go together.)"],
["তোমরা","tomra","you all (informal)","pronouns","pronoun","তোমরা কি খাবে? (tomra ki khabe — What will you all eat?)"],
["আপনারা","apnara","you all (formal)","pronouns","pronoun","আপনারা কোথা থেকে এসেছেন? (apnara kotha theke eshechen — Where have you all come from?)"],
["তারা","tara","they","pronouns","pronoun","তারা বাজারে গেছে। (tara bajare geche — They have gone to the market.)"],
["এটা","eta","this (thing)","pronouns","pronoun","এটা কী? (eta ki — What is this?)"],
["ওটা","ota","that (thing)","pronouns","pronoun","ওটা আমার বই। (ota amar boi — That is my book.)"],
["এই","ei","this","pronouns","pronoun","এই বাড়িটা সুন্দর। (ei barita shundor — This house is beautiful.)"],
["ওই","oi","that","pronouns","pronoun","ওই মেয়েটি কে? (oi meye ti ke — Who is that girl?)"],
["কে","ke","who","pronouns","pronoun","সে কে? (she ke — Who is he/she?)"],
["কী","ki","what","pronouns","pronoun","তুমি কী চাও? (tumi ki chao — What do you want?)"],
["কোথায়","kothay","where","pronouns","pronoun","তুমি কোথায় থাকো? (tumi kothay thako — Where do you live?)"],
["কেন","keno","why","pronouns","pronoun","তুমি কেন কাঁদছ? (tumi keno kandcho — Why are you crying?)"],
["কখন","kokhon","when","pronouns","pronoun","তুমি কখন আসবে? (tumi kokhon ashbe — When will you come?)"],
["কিভাবে","kibhabe","how","pronouns","pronoun","তুমি কিভাবে এলে? (tumi kibhabe ele — How did you come?)"],
["নিজে","nije","self","pronouns","pronoun","আমি নিজে করব। (ami nije korbo — I will do it myself.)"],
["সব","shob","all / everything","pronouns","pronoun","সব ঠিক আছে। (shob thik achhe — Everything is alright.)"],
["কেউ","keu","someone","pronouns","pronoun","কেউ দরজায় আছে। (keu dorjay achhe — Someone is at the door.)"],
["কিছু","kichhu","something / some","pronouns","pronoun","আমি কিছু খাব না। (ami kichhu khabo na — I will not eat anything.)"],
["প্রত্যেক","prottek","each / every","pronouns","pronoun","প্রত্যেক ছাত্র পাশ করেছে। (prottek chhatro pash korechhe — Every student has passed.)"],

// ─── NUMBERS (30) ───
["এক","ek","one","numbers","number"],
["দুই","dui","two","numbers","number"],
["তিন","tin","three","numbers","number"],
["চার","char","four","numbers","number"],
["পাঁচ","pach","five","numbers","number"],
["ছয়","chhoy","six","numbers","number"],
["সাত","shat","seven","numbers","number"],
["আট","at","eight","numbers","number"],
["নয়","noy","nine","numbers","number"],
["দশ","dosh","ten","numbers","number"],
["এগারো","egaro","eleven","numbers","number"],
["বারো","baro","twelve","numbers","number"],
["তেরো","tero","thirteen","numbers","number"],
["চৌদ্দ","chouddo","fourteen","numbers","number"],
["পনেরো","ponero","fifteen","numbers","number"],
["ষোলো","sholo","sixteen","numbers","number"],
["সতেরো","shotero","seventeen","numbers","number"],
["আঠারো","atharo","eighteen","numbers","number"],
["উনিশ","unish","nineteen","numbers","number"],
["বিশ","bish","twenty","numbers","number"],
["ত্রিশ","trish","thirty","numbers","number"],
["চল্লিশ","chollish","forty","numbers","number"],
["পঞ্চাশ","ponchash","fifty","numbers","number"],
["ষাট","shat","sixty","numbers","number"],
["সত্তর","shottor","seventy","numbers","number"],
["আশি","ashi","eighty","numbers","number"],
["নব্বই","nobboi","ninety","numbers","number"],
["একশো","eksho","one hundred","numbers","number"],
["হাজার","hajar","thousand","numbers","number"],
["লাখ","lakh","hundred thousand","numbers","number"],

// ─── FAMILY (30) ───
["মা","ma","mother","family","noun"],
["বাবা","baba","father","family","noun"],
["ভাই","bhai","brother","family","noun"],
["বোন","bon","sister","family","noun"],
["দাদা","dada","elder brother / paternal grandfather","family","noun"],
["দিদি","didi","elder sister","family","noun"],
["ছেলে","chhele","son / boy","family","noun"],
["মেয়ে","meye","daughter / girl","family","noun"],
["স্বামী","shami","husband","family","noun"],
["স্ত্রী","stri","wife","family","noun"],
["দাদু","dadu","paternal grandfather","family","noun"],
["দিদা","dida","paternal grandmother","family","noun"],
["নানা","nana","maternal grandfather","family","noun"],
["নানি","nani","maternal grandmother","family","noun"],
["কাকা","kaka","paternal uncle","family","noun"],
["কাকি","kaki","paternal aunt (uncle's wife)","family","noun"],
["মামা","mama","maternal uncle","family","noun"],
["মামি","mami","maternal aunt (uncle's wife)","family","noun"],
["পিসি","pishi","paternal aunt (father's sister)","family","noun"],
["মাসি","mashi","maternal aunt (mother's sister)","family","noun"],
["জামাই","jamai","son-in-law","family","noun"],
["বউ","bou","wife / bride / daughter-in-law","family","noun"],
["শিশু","shishu","baby / infant","family","noun"],
["পরিবার","poribar","family","family","noun"],
["বন্ধু","bondhu","friend","family","noun"],
["প্রতিবেশী","protibeshi","neighbor","family","noun"],
["মানুষ","manush","person / human","family","noun"],
["লোক","lok","person / people","family","noun"],
["সন্তান","shontan","child / offspring","family","noun"],
["আত্মীয়","attiyo","relative","family","noun"],

// ─── BODY (30) ───
["মাথা","matha","head","body","noun"],
["চোখ","chokh","eye","body","noun"],
["কান","kan","ear","body","noun"],
["নাক","nak","nose","body","noun"],
["মুখ","mukh","mouth / face","body","noun"],
["দাঁত","dat","tooth / teeth","body","noun"],
["জিভ","jibh","tongue","body","noun"],
["গলা","gola","throat / neck","body","noun"],
["হাত","hat","hand / arm","body","noun"],
["পা","pa","foot / leg","body","noun"],
["আঙুল","angul","finger","body","noun"],
["পেট","pet","stomach / belly","body","noun"],
["পিঠ","pith","back","body","noun"],
["বুক","buk","chest","body","noun"],
["হৃদয়","hridoy","heart","body","noun"],
["রক্ত","rokto","blood","body","noun"],
["হাড়","har","bone","body","noun"],
["চামড়া","chamra","skin","body","noun"],
["চুল","chul","hair","body","noun"],
["ঠোঁট","thot","lip","body","noun"],
["কপাল","kopal","forehead","body","noun"],
["গাল","gal","cheek","body","noun"],
["কাঁধ","kadh","shoulder","body","noun"],
["কোমর","komor","waist","body","noun"],
["হাঁটু","hatu","knee","body","noun"],
["শরীর","shorir","body","body","noun"],
["মন","mon","mind / heart (emotional)","body","noun"],
["প্রাণ","pran","life / soul","body","noun"],
["শক্তি","shokti","strength / power","body","noun"],
["স্বাস্থ্য","shasthyo","health","body","noun"],

// ─── FOOD & DRINK (45) ───
["খাবার","khabar","food","food","noun"],
["জল","jol","water","food","noun"],
["পানি","pani","water","food","noun"],
["ভাত","bhat","rice (cooked)","food","noun"],
["চাল","chal","rice (uncooked)","food","noun"],
["রুটি","ruti","bread / roti","food","noun"],
["ডাল","dal","lentils / dal","food","noun"],
["মাছ","machh","fish","food","noun"],
["মাংস","mangsho","meat","food","noun"],
["মুরগি","murgi","chicken","food","noun"],
["ডিম","dim","egg","food","noun"],
["দুধ","dudh","milk","food","noun"],
["চা","cha","tea","food","noun"],
["চিনি","chini","sugar","food","noun"],
["লবণ","lobon","salt","food","noun"],
["নুন","nun","salt","food","noun"],
["মশলা","moshla","spice","food","noun"],
["তেল","tel","oil","food","noun"],
["ঘি","ghi","ghee","food","noun"],
["আম","am","mango","food","noun"],
["কলা","kola","banana","food","noun"],
["আপেল","apel","apple","food","noun"],
["কমলা","komla","orange","food","noun"],
["আলু","alu","potato","food","noun"],
["পেঁয়াজ","peyaj","onion","food","noun"],
["রসুন","roshun","garlic","food","noun"],
["আদা","ada","ginger","food","noun"],
["মরিচ","morich","chili","food","noun"],
["টমেটো","tometo","tomato","food","noun"],
["শাক","shak","leafy greens","food","noun"],
["সবজি","shobji","vegetable","food","noun"],
["ফল","phol","fruit","food","noun"],
["মিষ্টি","mishti","sweet / dessert","food","noun"],
["দই","doi","yogurt","food","noun"],
["ননী","noni","cream / butter","food","noun"],
["পাউরুটি","pauruti","bread (loaf)","food","noun"],
["বিস্কুট","biskut","biscuit","food","noun"],
["কেক","kek","cake","food","noun"],
["নারকেল","narkel","coconut","food","noun"],
["পান","pan","betel leaf","food","noun"],
["সুপ","shup","soup","food","noun"],
["তরকারি","torkari","curry","food","noun"],
["ভাজা","bhaja","fried","food","adjective"],
["কাঁচা","kacha","raw / unripe","food","adjective"],
["পাকা","paka","ripe / cooked","food","adjective"],

// ─── ANIMALS (25) ───
["গরু","goru","cow","animals","noun"],
["ছাগল","chhagol","goat","animals","noun"],
["কুকুর","kukur","dog","animals","noun"],
["বিড়াল","biral","cat","animals","noun"],
["ঘোড়া","ghora","horse","animals","noun"],
["হাতি","hati","elephant","animals","noun"],
["বাঘ","bagh","tiger","animals","noun"],
["সিংহ","shingho","lion","animals","noun"],
["সাপ","shap","snake","animals","noun"],
["মাছ","machh","fish","animals","noun"],
["পাখি","pakhi","bird","animals","noun"],
["মুরগি","murgi","chicken / hen","animals","noun"],
["হাঁস","hash","duck","animals","noun"],
["ব্যাঙ","byang","frog","animals","noun"],
["মশা","mosha","mosquito","animals","noun"],
["মাছি","machhi","fly (insect)","animals","noun"],
["মৌমাছি","moumachhi","bee","animals","noun"],
["পিঁপড়া","pipra","ant","animals","noun"],
["প্রজাপতি","projapoti","butterfly","animals","noun"],
["কাক","kak","crow","animals","noun"],
["চড়ুই","chorui","sparrow","animals","noun"],
["ময়ূর","moyur","peacock","animals","noun"],
["ভালুক","bhaluk","bear","animals","noun"],
["বানর","banor","monkey","animals","noun"],
["উট","ut","camel","animals","noun"],

// ─── COLORS (15) ───
["লাল","lal","red","colors","adjective"],
["নীল","nil","blue","colors","adjective"],
["সবুজ","shobuj","green","colors","adjective"],
["হলুদ","holud","yellow","colors","adjective"],
["সাদা","shada","white","colors","adjective"],
["কালো","kalo","black","colors","adjective"],
["বাদামি","badami","brown","colors","adjective"],
["কমলা","komla","orange","colors","adjective"],
["গোলাপি","golapi","pink","colors","adjective"],
["বেগুনি","beguni","purple","colors","adjective"],
["ধূসর","dhushor","gray","colors","adjective"],
["সোনালি","shonali","golden","colors","adjective"],
["রুপোলি","rupoli","silver","colors","adjective"],
["গাঢ়","garho","dark / deep","colors","adjective"],
["হালকা","halka","light / pale","colors","adjective"],

// ─── TIME & CALENDAR (35) ───
["সময়","shomoy","time","time","noun"],
["এখন","ekhon","now","time","adverb"],
["আজ","aj","today","time","adverb"],
["কাল","kal","yesterday / tomorrow","time","adverb"],
["পরশু","porshu","day after tomorrow / day before yesterday","time","adverb"],
["সকাল","shokal","morning","time","noun"],
["দুপুর","dupur","noon / afternoon","time","noun"],
["বিকেল","bikel","late afternoon / evening","time","noun"],
["সন্ধ্যা","shondhya","evening / dusk","time","noun"],
["রাত","rat","night","time","noun"],
["দিন","din","day","time","noun"],
["রাত","rat","night","time","noun"],
["সপ্তাহ","shoptaho","week","time","noun"],
["মাস","mash","month","time","noun"],
["বছর","bochor","year","time","noun"],
["ঘণ্টা","ghonta","hour","time","noun"],
["মিনিট","minit","minute","time","noun"],
["সেকেন্ড","shekend","second","time","noun"],
["সোমবার","shombar","Monday","time","noun"],
["মঙ্গলবার","mongolbar","Tuesday","time","noun"],
["বুধবার","budhbar","Wednesday","time","noun"],
["বৃহস্পতিবার","brihoshpotibar","Thursday","time","noun"],
["শুক্রবার","shukrobar","Friday","time","noun"],
["শনিবার","shonibar","Saturday","time","noun"],
["রবিবার","robibar","Sunday","time","noun"],
["জানুয়ারি","january","January","time","noun"],
["ফেব্রুয়ারি","february","February","time","noun"],
["মার্চ","march","March","time","noun"],
["এপ্রিল","april","April","time","noun"],
["মে","me","May","time","noun"],
["জুন","jun","June","time","noun"],
["জুলাই","julai","July","time","noun"],
["আগস্ট","agost","August","time","noun"],
["সেপ্টেম্বর","sheptember","September","time","noun"],
["ঋতু","ritu","season","time","noun"],

// ─── NATURE & WEATHER (30) ───
["আকাশ","akash","sky","nature","noun"],
["সূর্য","shurjo","sun","nature","noun"],
["চাঁদ","chad","moon","nature","noun"],
["তারা","tara","star","nature","noun"],
["মেঘ","megh","cloud","nature","noun"],
["বৃষ্টি","brishti","rain","nature","noun"],
["বাতাস","batash","wind","nature","noun"],
["ঝড়","jhor","storm","nature","noun"],
["রোদ","rod","sunlight / sunshine","nature","noun"],
["ছায়া","chhaya","shadow / shade","nature","noun"],
["গাছ","gachh","tree","nature","noun"],
["ফুল","phul","flower","nature","noun"],
["পাতা","pata","leaf","nature","noun"],
["ঘাস","ghash","grass","nature","noun"],
["মাটি","mati","soil / earth","nature","noun"],
["পাথর","pathor","stone / rock","nature","noun"],
["নদী","nodi","river","nature","noun"],
["সমুদ্র","shomuddro","sea / ocean","nature","noun"],
["পাহাড়","pahar","hill / mountain","nature","noun"],
["বন","bon","forest","nature","noun"],
["জঙ্গল","jongol","jungle","nature","noun"],
["আগুন","agun","fire","nature","noun"],
["ধোঁয়া","dhoya","smoke","nature","noun"],
["বরফ","borof","ice / snow","nature","noun"],
["কাদা","kada","mud","nature","noun"],
["বালি","bali","sand","nature","noun"],
["সাগর","shagor","sea","nature","noun"],
["দ্বীপ","dip","island","nature","noun"],
["পুকুর","pukur","pond","nature","noun"],
["ঢেউ","dheu","wave","nature","noun"],

// ─── HOME & OBJECTS (40) ───
["ঘর","ghor","house / room","home","noun"],
["বাড়ি","bari","home / house","home","noun"],
["দরজা","dorja","door","home","noun"],
["জানালা","janala","window","home","noun"],
["ছাদ","chhad","roof","home","noun"],
["মেঝে","mejhe","floor","home","noun"],
["দেয়াল","deyal","wall","home","noun"],
["সিঁড়ি","shiri","stairs","home","noun"],
["চেয়ার","cheyar","chair","home","noun"],
["টেবিল","tebil","table","home","noun"],
["বিছানা","bichhana","bed","home","noun"],
["বালিশ","balish","pillow","home","noun"],
["চাদর","chador","bedsheet / shawl","home","noun"],
["কম্বল","kombol","blanket","home","noun"],
["আয়না","ayna","mirror","home","noun"],
["ঘড়ি","ghori","clock / watch","home","noun"],
["চাবি","chabi","key","home","noun"],
["তালা","tala","lock","home","noun"],
["বাতি","bati","lamp / light","home","noun"],
["পাখা","pakha","fan","home","noun"],
["ছবি","chhobi","picture / photo","home","noun"],
["বই","boi","book","home","noun"],
["কাগজ","kagoj","paper","home","noun"],
["কলম","kolom","pen","home","noun"],
["থালা","thala","plate","home","noun"],
["বাটি","bati","bowl","home","noun"],
["গ্লাস","glass","glass / cup","home","noun"],
["চামচ","chamoch","spoon","home","noun"],
["ছুরি","chhuri","knife","home","noun"],
["হাঁড়ি","hari","cooking pot","home","noun"],
["ঝাড়ু","jharu","broom","home","noun"],
["সাবান","shaban","soap","home","noun"],
["তোয়ালে","toyale","towel","home","noun"],
["জামা","jama","shirt / clothes","home","noun"],
["জুতো","juto","shoes","home","noun"],
["ছাতা","chhata","umbrella","home","noun"],
["ব্যাগ","byag","bag","home","noun"],
["টাকা","taka","money","home","noun"],
["ফোন","phone","phone","home","noun"],
["কম্পিউটার","computer","computer","home","noun"],

// ─── PLACES (30) ───
["দেশ","desh","country","places","noun"],
["শহর","shohor","city","places","noun"],
["গ্রাম","gram","village","places","noun"],
["রাস্তা","rasta","road / street","places","noun"],
["বাজার","bajar","market / bazaar","places","noun"],
["দোকান","dokan","shop / store","places","noun"],
["স্কুল","school","school","places","noun"],
["কলেজ","college","college","places","noun"],
["বিশ্ববিদ্যালয়","bishbobiddyaloy","university","places","noun"],
["হাসপাতাল","hashpatal","hospital","places","noun"],
["মসজিদ","moshjid","mosque","places","noun"],
["মন্দির","mondir","temple","places","noun"],
["গির্জা","girja","church","places","noun"],
["অফিস","office","office","places","noun"],
["ব্যাংক","bank","bank","places","noun"],
["পার্ক","park","park","places","noun"],
["মাঠ","math","field / playground","places","noun"],
["নদী","nodi","river","places","noun"],
["সেতু","shetu","bridge","places","noun"],
["স্টেশন","station","station","places","noun"],
["বিমানবন্দর","bimanbondor","airport","places","noun"],
["হোটেল","hotel","hotel / restaurant","places","noun"],
["রেস্তোরাঁ","restoram","restaurant","places","noun"],
["সিনেমা","cinema","cinema","places","noun"],
["লাইব্রেরি","library","library","places","noun"],
["পোস্ট অফিস","post office","post office","places","noun"],
["থানা","thana","police station","places","noun"],
["কারখানা","karkhana","factory","places","noun"],
["পৃথিবী","prithibi","world / earth","places","noun"],
["জায়গা","jayga","place / location","places","noun"],

// ─── COMMON VERBS (120) ───
["করা","kora","to do / to make","verbs","verb"],
["হওয়া","howa","to be / to become","verbs","verb"],
["যাওয়া","jaowa","to go","verbs","verb"],
["আসা","asha","to come","verbs","verb"],
["দেওয়া","deowa","to give","verbs","verb"],
["নেওয়া","neowa","to take","verbs","verb"],
["বলা","bola","to say / to tell","verbs","verb"],
["খাওয়া","khaowa","to eat","verbs","verb"],
["পড়া","pora","to read / to study / to fall","verbs","verb"],
["লেখা","lekha","to write","verbs","verb"],
["দেখা","dekha","to see / to look","verbs","verb"],
["শোনা","shona","to hear / to listen","verbs","verb"],
["জানা","jana","to know","verbs","verb"],
["বোঝা","bojha","to understand","verbs","verb"],
["ভাবা","bhaba","to think","verbs","verb"],
["চাওয়া","chaowa","to want / to desire","verbs","verb"],
["পাওয়া","paowa","to get / to receive","verbs","verb"],
["রাখা","rakha","to keep / to put","verbs","verb"],
["ধরা","dhora","to hold / to catch","verbs","verb"],
["ফেলা","phela","to throw / to drop","verbs","verb"],
["থাকা","thaka","to stay / to live / to exist","verbs","verb"],
["বসা","bosha","to sit","verbs","verb"],
["দাঁড়ানো","darano","to stand","verbs","verb"],
["শোওয়া","showa","to sleep / to lie down","verbs","verb"],
["ঘুমানো","ghumano","to sleep","verbs","verb"],
["ওঠা","otha","to get up / to rise","verbs","verb"],
["চলা","chola","to move / to walk","verbs","verb"],
["হাঁটা","hata","to walk","verbs","verb"],
["দৌড়ানো","dourano","to run","verbs","verb"],
["খেলা","khela","to play","verbs","verb"],
["গাওয়া","gaowa","to sing","verbs","verb"],
["নাচা","nacha","to dance","verbs","verb"],
["হাসা","hasha","to laugh / to smile","verbs","verb"],
["কাঁদা","kada","to cry","verbs","verb"],
["ভালোবাসা","bhalobasha","to love","verbs","verb"],
["পছন্দ করা","pochhondo kora","to like","verbs","verb"],
["ঘৃণা করা","ghrina kora","to hate","verbs","verb"],
["ভয় পাওয়া","bhoy paowa","to be afraid / to fear","verbs","verb"],
["মারা","mara","to hit / to beat","verbs","verb"],
["কাটা","kata","to cut","verbs","verb"],
["ভাঙা","bhanga","to break","verbs","verb"],
["খোলা","khola","to open","verbs","verb"],
["বন্ধ করা","bondho kora","to close / to shut","verbs","verb"],
["ধোওয়া","dhowa","to wash","verbs","verb"],
["রান্না করা","ranna kora","to cook","verbs","verb"],
["কেনা","kena","to buy","verbs","verb"],
["বেচা","becha","to sell","verbs","verb"],
["পাঠানো","pathano","to send","verbs","verb"],
["আনা","ana","to bring","verbs","verb"],
["নিয়ে যাওয়া","niye jaowa","to take away","verbs","verb"],
["ফেরা","phera","to return","verbs","verb"],
["বেড়ানো","berano","to travel / visit","verbs","verb"],
["শুরু করা","shuru kora","to start / to begin","verbs","verb"],
["শেষ করা","shesh kora","to finish / to end","verbs","verb"],
["পারা","para","can / to be able to","verbs","verb"],
["লাগা","laga","to feel / to need / to take (time)","verbs","verb"],
["মনে করা","mone kora","to remember / to think","verbs","verb"],
["ভুলে যাওয়া","bhule jaowa","to forget","verbs","verb"],
["চেষ্টা করা","cheshta kora","to try","verbs","verb"],
["সাহায্য করা","shahajyo kora","to help","verbs","verb"],
["কাজ করা","kaj kora","to work","verbs","verb"],
["শেখা","shekha","to learn","verbs","verb"],
["শেখানো","shekhano","to teach","verbs","verb"],
["বিশ্বাস করা","bishshash kora","to believe / to trust","verbs","verb"],
["মরা","mora","to die","verbs","verb"],
["বাঁচা","bacha","to live / to survive","verbs","verb"],
["জন্মানো","jonmano","to be born","verbs","verb"],
["বড় হওয়া","boro howa","to grow up","verbs","verb"],
["পরা","pora","to wear","verbs","verb"],
["খোঁজা","khoja","to look for / to search","verbs","verb"],
["পেতে","pete","to find / to get","verbs","verb"],
["হারানো","harano","to lose","verbs","verb"],
["জেতা","jeta","to win","verbs","verb"],
["তৈরি করা","toiri kora","to prepare / to make","verbs","verb"],
["বদলানো","bodlano","to change","verbs","verb"],
["চেনা","chena","to recognize / to know (a person)","verbs","verb"],
["ডাকা","daka","to call","verbs","verb"],
["উত্তর দেওয়া","uttor deowa","to answer / to reply","verbs","verb"],
["জিজ্ঞেস করা","jiggesh kora","to ask (a question)","verbs","verb"],
["অপেক্ষা করা","opekkha kora","to wait","verbs","verb"],
["তাড়াতাড়ি করা","taratari kora","to hurry","verbs","verb"],
["ঘোরা","ghora","to roam / to wander","verbs","verb"],
["পৌঁছানো","pouchhano","to arrive / to reach","verbs","verb"],
["বসবাস করা","boshobash kora","to reside","verbs","verb"],
["গড়া","gora","to build","verbs","verb"],
["মেরামত করা","meramot kora","to repair","verbs","verb"],
["পরিষ্কার করা","porishkar kora","to clean","verbs","verb"],
["ব্যবহার করা","bybohar kora","to use","verbs","verb"],
["নষ্ট করা","noshto kora","to destroy / to waste","verbs","verb"],
["রক্ষা করা","rokkha kora","to protect","verbs","verb"],
["মানা","mana","to obey / to agree","verbs","verb"],
["প্রার্থনা করা","prarthona kora","to pray","verbs","verb"],
["গোসল করা","goshol kora","to bathe","verbs","verb"],
["টানা","tana","to pull","verbs","verb"],
["ঠেলা","thela","to push","verbs","verb"],
["ওড়া","ora","to fly","verbs","verb"],
["সাঁতার কাটা","shatar kata","to swim","verbs","verb"],
["পড়া","pora","to fall","verbs","verb"],
["ওঠা","otha","to climb / to rise","verbs","verb"],
["নামা","nama","to descend / to get down","verbs","verb"],
["ঘুরে দেখা","ghure dekha","to look around / visit","verbs","verb"],
["ভুল করা","bhul kora","to make a mistake","verbs","verb"],
["ঠিক করা","thik kora","to fix / to decide","verbs","verb"],
["আলোচনা করা","alochona kora","to discuss","verbs","verb"],
["রাজি হওয়া","raji howa","to agree","verbs","verb"],
["প্রতিজ্ঞা করা","protigga kora","to promise","verbs","verb"],
["পছন্দ হওয়া","pochhondo howa","to be liked","verbs","verb"],
["ক্ষমা করা","khoma kora","to forgive","verbs","verb"],
["দরকার হওয়া","dorkar howa","to be needed","verbs","verb"],
["সম্ভব হওয়া","shombhob howa","to be possible","verbs","verb"],
["শুনানো","shunano","to narrate / tell","verbs","verb"],
["ঝগড়া করা","jhogra kora","to quarrel / fight","verbs","verb"],
["চিনতে পারা","chinte para","to be able to recognize","verbs","verb"],
["ছোঁয়া","chhoya","to touch","verbs","verb"],
["গুনা","gona","to count","verbs","verb"],
["মাপা","mapa","to measure","verbs","verb"],
["ভরা","bhora","to fill","verbs","verb"],
["ঢালা","dhala","to pour","verbs","verb"],
["মেশা","mesha","to mix","verbs","verb"],
["জ্বালানো","jbalano","to light / to burn","verbs","verb"],
["নেভানো","nebhano","to extinguish","verbs","verb"],

// ─── COMMON ADJECTIVES (80) ───
["ভালো","bhalo","good","adjectives","adjective"],
["খারাপ","kharap","bad","adjectives","adjective"],
["বড়","boro","big / elder","adjectives","adjective"],
["ছোটো","chhoto","small / younger","adjectives","adjective"],
["নতুন","notun","new","adjectives","adjective"],
["পুরোনো","purono","old (thing)","adjectives","adjective"],
["বুড়ো","buro","old (person)","adjectives","adjective"],
["তরুণ","torun","young","adjectives","adjective"],
["সুন্দর","shundor","beautiful","adjectives","adjective"],
["কুৎসিত","kutsit","ugly","adjectives","adjective"],
["লম্বা","lomba","tall / long","adjectives","adjective"],
["খাটো","khato","short (height)","adjectives","adjective"],
["মোটা","mota","fat / thick","adjectives","adjective"],
["পাতলা","patla","thin","adjectives","adjective"],
["গরম","gorom","hot / warm","adjectives","adjective"],
["ঠান্ডা","thanda","cold / cool","adjectives","adjective"],
["সহজ","shohoj","easy","adjectives","adjective"],
["কঠিন","kothin","hard / difficult","adjectives","adjective"],
["দ্রুত","druto","fast / quick","adjectives","adjective"],
["ধীর","dhir","slow","adjectives","adjective"],
["কাছে","kachhe","near","adjectives","adjective"],
["দূরে","dure","far","adjectives","adjective"],
["ওপরে","opore","above / up","adjectives","adjective"],
["নিচে","niche","below / down","adjectives","adjective"],
["ডানে","dane","right (direction)","adjectives","adjective"],
["বাঁয়ে","baye","left (direction)","adjectives","adjective"],
["সামনে","shamne","in front","adjectives","adjective"],
["পেছনে","pechhone","behind","adjectives","adjective"],
["ভেতরে","bhetore","inside","adjectives","adjective"],
["বাইরে","baire","outside","adjectives","adjective"],
["পরিষ্কার","porishkar","clean","adjectives","adjective"],
["নোংরা","nongra","dirty","adjectives","adjective"],
["শক্ত","shokto","hard / strong","adjectives","adjective"],
["নরম","norom","soft","adjectives","adjective"],
["ভেজা","bheja","wet","adjectives","adjective"],
["শুকনো","shukno","dry","adjectives","adjective"],
["খালি","khali","empty / only","adjectives","adjective"],
["ভরা","bhora","full","adjectives","adjective"],
["সত্যি","shotti","true / real","adjectives","adjective"],
["মিথ্যা","mitthya","false / lie","adjectives","adjective"],
["ঠিক","thik","right / correct","adjectives","adjective"],
["ভুল","bhul","wrong / mistake","adjectives","adjective"],
["সম্ভব","shombhob","possible","adjectives","adjective"],
["অসম্ভব","oshombhob","impossible","adjectives","adjective"],
["দরকার","dorkar","necessary / needed","adjectives","adjective"],
["গুরুত্বপূর্ণ","guruttopurno","important","adjectives","adjective"],
["সুস্থ","shustho","healthy / well","adjectives","adjective"],
["অসুস্থ","oshustho","sick / unwell","adjectives","adjective"],
["খুশি","khushi","happy","adjectives","adjective"],
["দুঃখী","dukhkhi","sad","adjectives","adjective"],
["রাগী","ragi","angry","adjectives","adjective"],
["ক্লান্ত","klanto","tired","adjectives","adjective"],
["ক্ষুধার্ত","khudarto","hungry","adjectives","adjective"],
["তৃষ্ণার্ত","trishnarto","thirsty","adjectives","adjective"],
["ধনী","dhoni","rich","adjectives","adjective"],
["গরিব","gorib","poor","adjectives","adjective"],
["সস্তা","shosta","cheap","adjectives","adjective"],
["দামি","dami","expensive","adjectives","adjective"],
["প্রথম","prothom","first","adjectives","adjective"],
["শেষ","shesh","last / end","adjectives","adjective"],
["পরের","porer","next","adjectives","adjective"],
["আগের","ager","previous","adjectives","adjective"],
["আলাদা","alada","separate / different","adjectives","adjective"],
["একই","eki","same","adjectives","adjective"],
["সব","shob","all","adjectives","adjective"],
["কিছু","kichhu","some","adjectives","adjective"],
["অনেক","onek","many / much","adjectives","adjective"],
["কম","kom","few / less","adjectives","adjective"],
["বেশি","beshi","more / much","adjectives","adjective"],
["যথেষ্ট","jotheshto","enough","adjectives","adjective"],
["আস্ত","asto","whole / entire","adjectives","adjective"],
["অর্ধেক","ordhek","half","adjectives","adjective"],
["পুরো","puro","whole / complete","adjectives","adjective"],
["বিশেষ","bishesh","special","adjectives","adjective"],
["সাধারণ","shadharon","ordinary / common","adjectives","adjective"],
["মুক্ত","mukto","free","adjectives","adjective"],
["ব্যস্ত","bysto","busy","adjectives","adjective"],
["চুপ","chup","quiet / silent","adjectives","adjective"],
["জোরে","jore","loud / loudly","adjectives","adjective"],
["আস্তে","aste","slowly / softly","adjectives","adjective"],

// ─── COMMON ADVERBS & PARTICLES (35) ───
["আবার","abar","again","adverbs","adverb"],
["এখনো","ekhono","still / yet","adverbs","adverb"],
["আর","ar","and / more / else","adverbs","particle"],
["না","na","no / not","adverbs","particle"],
["হ্যাঁ","hya","yes","adverbs","particle"],
["তাহলে","tahole","then / in that case","adverbs","conjunction"],
["কিন্তু","kintu","but","adverbs","conjunction"],
["কারণ","karon","because / reason","adverbs","conjunction"],
["যদি","jodi","if","adverbs","conjunction"],
["তবে","tobe","then / however","adverbs","conjunction"],
["অথবা","othoba","or","adverbs","conjunction"],
["এবং","ebong","and","adverbs","conjunction"],
["তাই","tai","so / therefore","adverbs","conjunction"],
["শুধু","shudhu","only / just","adverbs","adverb"],
["সবসময়","shobshomoy","always","adverbs","adverb"],
["কখনো","kokhono","ever / sometimes","adverbs","adverb"],
["কখনোই না","kokhonoi na","never","adverbs","adverb"],
["প্রায়","pray","almost / often","adverbs","adverb"],
["হয়তো","hoyto","maybe / perhaps","adverbs","adverb"],
["অবশ্যই","oboshyoi","of course / certainly","adverbs","adverb"],
["সত্যিই","shottyii","really / truly","adverbs","adverb"],
["খুব","khub","very","adverbs","adverb"],
["অনেক","onek","very much / a lot","adverbs","adverb"],
["একটু","ektu","a little","adverbs","adverb"],
["তাড়াতাড়ি","taratari","quickly","adverbs","adverb"],
["ধীরে ধীরে","dhire dhire","slowly","adverbs","adverb"],
["এখানে","ekhane","here","adverbs","adverb"],
["সেখানে","shekhane","there","adverbs","adverb"],
["কোথাও","kothao","somewhere","adverbs","adverb"],
["সর্বত্র","shorbotrô","everywhere","adverbs","adverb"],
["একসাথে","ekshathé","together","adverbs","adverb"],
["আলাদাভাবে","aladabhabe","separately","adverbs","adverb"],
["সরাসরি","shorashori","directly","adverbs","adverb"],
["বিশেষভাবে","bisheshbhabe","especially","adverbs","adverb"],
["সাধারণত","shadharonoto","usually / generally","adverbs","adverb"],

// ─── GREETINGS & EXPRESSIONS (30) ───
["নমস্কার","nomoshkar","hello (Hindu greeting)","expressions","expression","নমস্কার, কেমন আছেন? (nomoshkar, kemon achhen — Hello, how are you?)"],
["আসসালামু আলাইকুম","assalamu alaikum","hello (Muslim greeting)","expressions","expression","আসসালামু আলাইকুম, ভালো আছি। (assalamu alaikum, bhalo achhi — Hello, I am fine.)"],
["ধন্যবাদ","dhonnobad","thank you","expressions","expression","সাহায্যের জন্য ধন্যবাদ। (shahajyer jonno dhonnobad — Thank you for the help.)"],
["দয়া করে","doya kore","please","expressions","expression","দয়া করে এখানে বসুন। (doya kore ekhane boshun — Please sit here.)"],
["মাফ করবেন","maph korben","excuse me / sorry (formal)","expressions","expression","মাফ করবেন, আমি দেরি করেছি। (maph korben, ami deri korechhi — Excuse me, I am late.)"],
["দুঃখিত","dukhkhito","sorry","expressions","expression","আমি সত্যিই দুঃখিত। (ami shottyi dukhkhito — I am truly sorry.)"],
["স্বাগতম","shagatom","welcome","expressions","expression","আমাদের বাড়িতে স্বাগতম। (amader barite shagatom — Welcome to our home.)"],
["শুভ সকাল","shubho shokal","good morning","expressions","expression","শুভ সকাল! কেমন আছেন? (shubho shokal! kemon achhen — Good morning! How are you?)"],
["শুভ রাত্রি","shubho ratri","good night","expressions","expression","শুভ রাত্রি, ভালো ঘুমাও। (shubho ratri, bhalo ghumao — Good night, sleep well.)"],
["কেমন আছেন","kemon achhen","how are you (formal)","expressions","expression","কেমন আছেন আপনি? (kemon achhen apni — How are you?)"],
["ভালো আছি","bhalo achhi","I am fine","expressions","expression","ধন্যবাদ, আমি ভালো আছি। (dhonnobad, ami bhalo achhi — Thank you, I am fine.)"],
["আপনার নাম কী","apnar nam ki","what is your name","expressions","expression","আপনার নাম কী, ভাই? (apnar nam ki, bhai — What is your name, friend?)"],
["আমার নাম","amar nam","my name is","expressions","expression","আমার নাম রাহুল। (amar nam Rahul — My name is Rahul.)"],
["হ্যাঁ","hya","yes","expressions","expression","হ্যাঁ, আমি যাব। (hya, ami jabo — Yes, I will go.)"],
["না","na","no","expressions","expression","না, আমি পারব না। (na, ami parbo na — No, I cannot.)"],
["ঠিক আছে","thik achhe","okay / alright","expressions","expression","ঠিক আছে, চলো। (thik achhe, cholo — Okay, let's go.)"],
["বুঝেছি","bujhechhi","I understand","expressions","expression","আপনার কথা বুঝেছি। (apnar kotha bujhechhi — I understand what you're saying.)"],
["বুঝিনি","bujhini","I don't understand","expressions","expression","আমি বুঝিনি, আবার বলুন। (ami bujhini, abar bolun — I didn't understand, please say again.)"],
["আবার বলুন","abar bolun","say it again (formal)","expressions","expression","একটু আস্তে আবার বলুন। (ektu ashte abar bolun — Please say it again more slowly.)"],
["একটু দাঁড়ান","ektu daran","wait a moment (formal)","expressions","expression","একটু দাঁড়ান, আমি আসছি। (ektu daran, ami ashchhi — Wait a moment, I am coming.)"],
["চলুন","cholun","let's go (formal)","expressions","expression","চলুন, বাজারে যাই। (cholun, bajare jai — Let's go to the market.)"],
["এসো","esho","come (informal)","expressions","expression","এসো, এখানে বসো। (esho, ekhane bosho — Come, sit here.)"],
["বসুন","boshun","sit down (formal)","expressions","expression","দয়া করে বসুন। (doya kore boshun — Please sit down.)"],
["কত দাম","koto dam","how much (price)","expressions","expression","এটার কত দাম? (etar koto dam — How much does this cost?)"],
["আমি বাংলা শিখছি","ami bangla shikhchhi","I am learning Bengali","expressions","expression","আমি এখন বাংলা শিখছি। (ami ekhon bangla shikhchhi — I am now learning Bengali.)"],
["একটু সাহায্য করবেন","ektu shahajyo korben","can you help a little","expressions","expression","একটু সাহায্য করবেন, দয়া করে? (ektu shahajyo korben, doya kore — Can you help me a little, please?)"],
["আমি জানি না","ami jani na","I don't know","expressions","expression","আমি জানি না সে কোথায়। (ami jani na she kothay — I don't know where he is.)"],
["কোনো সমস্যা নেই","kono shomossha nei","no problem","expressions","expression","কোনো সমস্যা নেই, সব ঠিক আছে। (kono shomossha nei, shob thik achhe — No problem, everything is alright.)"],
["অভিনন্দন","obhinondon","congratulations","expressions","expression","অভিনন্দন, তোমার পরীক্ষায় পাশ করেছ! (obhinondon, tomar porikkhay pash korechho — Congratulations, you passed the exam!)"],
["বিদায়","biday","goodbye / farewell","expressions","expression","বিদায়, আবার দেখা হবে। (biday, abar dekha hobe — Goodbye, we will meet again.)"],

// ─── PROFESSIONS (25) ───
["শিক্ষক","shikkhok","teacher","professions","noun"],
["ডাক্তার","daktar","doctor","professions","noun"],
["ইঞ্জিনিয়ার","injiniyar","engineer","professions","noun"],
["উকিল","ukil","lawyer","professions","noun"],
["পুলিশ","pulish","police","professions","noun"],
["সৈনিক","shoinik","soldier","professions","noun"],
["কৃষক","krishok","farmer","professions","noun"],
["ব্যবসায়ী","byboshayee","businessman","professions","noun"],
["দোকানদার","dokandar","shopkeeper","professions","noun"],
["রাঁধুনি","radhuni","cook","professions","noun"],
["ড্রাইভার","draivar","driver","professions","noun"],
["ছাত্র","chatro","student (male)","professions","noun"],
["ছাত্রী","chatri","student (female)","professions","noun"],
["নার্স","narsh","nurse","professions","noun"],
["সাংবাদিক","shangbadik","journalist","professions","noun"],
["লেখক","lekhok","writer / author","professions","noun"],
["শিল্পী","shilpi","artist","professions","noun"],
["গায়ক","gayok","singer (male)","professions","noun"],
["অভিনেতা","obhineta","actor","professions","noun"],
["খেলোয়াড়","khelowar","player / athlete","professions","noun"],
["মন্ত্রী","montri","minister","professions","noun"],
["রাজনীতিবিদ","rajnitibid","politician","professions","noun"],
["বিজ্ঞানী","biggani","scientist","professions","noun"],
["ধোপা","dhopa","washerman","professions","noun"],
["নাপিত","napit","barber","professions","noun"],

// ─── TRANSPORT (15) ───
["গাড়ি","gari","car / vehicle","transport","noun"],
["বাস","bash","bus","transport","noun"],
["ট্রেন","tren","train","transport","noun"],
["রিকশা","riksha","rickshaw","transport","noun"],
["সাইকেল","saikel","bicycle","transport","noun"],
["মোটরসাইকেল","motorshaikel","motorcycle","transport","noun"],
["নৌকা","nouka","boat","transport","noun"],
["জাহাজ","jahaj","ship","transport","noun"],
["বিমান","biman","airplane","transport","noun"],
["অটো","auto","auto-rickshaw","transport","noun"],
["ট্যাক্সি","taxi","taxi","transport","noun"],
["হেলিকপ্টার","helicopter","helicopter","transport","noun"],
["চাকা","chaka","wheel","transport","noun"],
["রাস্তা","rasta","road","transport","noun"],
["যাত্রা","jatra","journey","transport","noun"],

// ─── CLOTHING (15) ───
["জামা","jama","shirt / dress","clothing","noun"],
["প্যান্ট","pant","pants","clothing","noun"],
["শাড়ি","shari","sari","clothing","noun"],
["লুঙ্গি","lungi","lungi (wraparound)","clothing","noun"],
["পাঞ্জাবি","panjabi","panjabi (tunic)","clothing","noun"],
["জুতো","juto","shoes","clothing","noun"],
["স্যান্ডেল","sandel","sandals","clothing","noun"],
["টুপি","tupi","hat / cap","clothing","noun"],
["ওড়না","orna","scarf / dupatta","clothing","noun"],
["কামিজ","kamij","kameez / tunic","clothing","noun"],
["সালোয়ার","salowar","salwar (trousers)","clothing","noun"],
["গয়না","goyna","jewelry","clothing","noun"],
["আংটি","angti","ring","clothing","noun"],
["চশমা","choshma","glasses / spectacles","clothing","noun"],
["ঘড়ি","ghori","watch","clothing","noun"],

// ─── EMOTIONS & STATES (25) ───
["সুখ","shukh","happiness","emotions","noun"],
["দুঃখ","dukhkho","sadness / sorrow","emotions","noun"],
["রাগ","rag","anger","emotions","noun"],
["ভয়","bhoy","fear","emotions","noun"],
["আনন্দ","anondo","joy / delight","emotions","noun"],
["ভালোবাসা","bhalobasha","love","emotions","noun"],
["ঘৃণা","ghrina","hatred","emotions","noun"],
["আশা","asha","hope","emotions","noun"],
["নিরাশা","nirasha","hopelessness","emotions","noun"],
["চিন্তা","chinta","worry / thought","emotions","noun"],
["শান্তি","shanti","peace","emotions","noun"],
["কষ্ট","koshto","pain / suffering","emotions","noun"],
["আরাম","aram","comfort / rest","emotions","noun"],
["লজ্জা","lojja","shame / embarrassment","emotions","noun"],
["গর্ব","gorbo","pride","emotions","noun"],
["ঈর্ষা","irsha","jealousy","emotions","noun"],
["বিস্ময়","bismoy","surprise / wonder","emotions","noun"],
["একাকী","ekaki","lonely","emotions","adjective"],
["উদ্বিগ্ন","udbigno","anxious / worried","emotions","adjective"],
["সন্তুষ্ট","shontushto","satisfied","emotions","adjective"],
["হতাশ","hotash","frustrated / disappointed","emotions","adjective"],
["উত্তেজিত","uttejito","excited","emotions","adjective"],
["বিরক্ত","birokto","annoyed","emotions","adjective"],
["নার্ভাস","narbhash","nervous","emotions","adjective"],
["আত্মবিশ্বাসী","attobishshashi","confident","emotions","adjective"],

// ─── EDUCATION & WORK (30) ───
["পড়াশোনা","porashona","study / education","education","noun"],
["স্কুল","school","school","education","noun"],
["ক্লাস","class","class","education","noun"],
["পরীক্ষা","porikkha","exam","education","noun"],
["বিষয়","bishoy","subject / topic","education","noun"],
["প্রশ্ন","proshno","question","education","noun"],
["উত্তর","uttor","answer / north","education","noun"],
["বাক্য","bakko","sentence","education","noun"],
["শব্দ","shobdo","word / sound","education","noun"],
["অক্ষর","okkhor","letter (alphabet)","education","noun"],
["ভাষা","bhasha","language","education","noun"],
["বাংলা","bangla","Bengali","education","noun"],
["ইংরেজি","ingreji","English","education","noun"],
["গণিত","gonit","mathematics","education","noun"],
["বিজ্ঞান","biggan","science","education","noun"],
["ইতিহাস","itihash","history","education","noun"],
["কাজ","kaj","work / job","education","noun"],
["চাকরি","chakri","job / employment","education","noun"],
["বেতন","beton","salary","education","noun"],
["মিটিং","meeting","meeting","education","noun"],
["প্রকল্প","prokolpo","project","education","noun"],
["সমস্যা","shomossha","problem","education","noun"],
["সমাধান","shomadhan","solution","education","noun"],
["ফলাফল","pholaphol","result","education","noun"],
["সাফল্য","shapholyo","success","education","noun"],
["ব্যর্থতা","byortota","failure","education","noun"],
["অভিজ্ঞতা","obhiggyota","experience","education","noun"],
["দক্ষতা","dokkhota","skill / ability","education","noun"],
["নিয়ম","niyom","rule","education","noun"],
["আইন","ain","law","education","noun"],

// ─── SOCIETY & RELIGION (25) ───
["সরকার","shorkar","government","society","noun"],
["রাষ্ট্র","rashtro","state / nation","society","noun"],
["জাতি","jati","nation / caste","society","noun"],
["ধর্ম","dhormo","religion","society","noun"],
["সংস্কৃতি","shongskriti","culture","society","noun"],
["ভোট","bhot","vote","society","noun"],
["অধিকার","odhikar","right (legal)","society","noun"],
["স্বাধীনতা","shadhinota","independence / freedom","society","noun"],
["যুদ্ধ","juddho","war","society","noun"],
["শান্তি","shanti","peace","society","noun"],
["সমাজ","shomaj","society","society","noun"],
["মানবাধিকার","manobadhikar","human rights","society","noun"],
["নারী","nari","woman","society","noun"],
["পুরুষ","purush","man","society","noun"],
["শিক্ষা","shikkha","education","society","noun"],
["ঈশ্বর","ishhor","God","society","noun"],
["আল্লাহ","allah","Allah / God","society","noun"],
["নামাজ","namaj","prayer (Islamic)","society","noun"],
["পূজা","puja","worship (Hindu)","society","noun"],
["উৎসব","utshob","festival","society","noun"],
["বিবাহ","bibaho","marriage / wedding","society","noun"],
["মৃত্যু","mrittu","death","society","noun"],
["জীবন","jibon","life","society","noun"],
["সংবাদ","shongbad","news","society","noun"],
["খবর","khobor","news","society","noun"],

// ─── ABSTRACT & MISC (60) ───
["কথা","kotha","word / speech / matter","abstract","noun"],
["কাজ","kaj","work / deed","abstract","noun"],
["জিনিস","jinish","thing / item","abstract","noun"],
["ব্যাপার","byapar","matter / affair","abstract","noun"],
["অবস্থা","obostha","condition / state","abstract","noun"],
["ধরন","dhoron","type / kind","abstract","noun"],
["উপায়","upay","way / method","abstract","noun"],
["কারণ","karon","reason / cause","abstract","noun"],
["ফল","phol","result / fruit","abstract","noun"],
["পথ","poth","path / way","abstract","noun"],
["দিক","dik","direction / side","abstract","noun"],
["তথ্য","tothyo","information / data","abstract","noun"],
["চিন্তা","chinta","thought / worry","abstract","noun"],
["মত","mot","opinion / like","abstract","noun"],
["ধারণা","dharona","idea / concept","abstract","noun"],
["অর্থ","ortho","meaning / money","abstract","noun"],
["মূল্য","mullyo","value / price","abstract","noun"],
["আকার","akar","size / shape","abstract","noun"],
["রং","rong","color","abstract","noun"],
["গন্ধ","gondho","smell","abstract","noun"],
["স্বাদ","shad","taste","abstract","noun"],
["শব্দ","shobdo","sound","abstract","noun"],
["আলো","alo","light","abstract","noun"],
["অন্ধকার","ondhokar","darkness","abstract","noun"],
["গতি","goti","speed / motion","abstract","noun"],
["ওজন","ojon","weight","abstract","noun"],
["দূরত্ব","durotto","distance","abstract","noun"],
["উচ্চতা","uchchota","height","abstract","noun"],
["সংখ্যা","shongkha","number / count","abstract","noun"],
["নাম","nam","name","abstract","noun"],
["ঠিকানা","thikana","address","abstract","noun"],
["সুযোগ","shujog","opportunity / chance","abstract","noun"],
["সময়","shomoy","time","abstract","noun"],
["ক্ষমতা","khomota","power / authority","abstract","noun"],
["ইচ্ছা","ichha","wish / desire","abstract","noun"],
["স্বপ্ন","shopno","dream","abstract","noun"],
["গল্প","golpo","story","abstract","noun"],
["ছবি","chhobi","picture / image","abstract","noun"],
["খেলা","khela","game / sport","abstract","noun"],
["গান","gan","song","abstract","noun"],
["নাচ","nach","dance","abstract","noun"],
["ভ্রমণ","bhromon","travel / trip","abstract","noun"],
["ছুটি","chhuti","holiday / vacation","abstract","noun"],
["ভুল","bhul","mistake / error","abstract","noun"],
["সাহায্য","shahajyo","help / assistance","abstract","noun"],
["দাম","dam","price","abstract","noun"],
["লাভ","labh","profit / benefit","abstract","noun"],
["ক্ষতি","khoti","loss / harm","abstract","noun"],
["বিপদ","bipod","danger","abstract","noun"],
["নিরাপদ","nirapod","safe","abstract","adjective"],
["বিপজ্জনক","bipojjonok","dangerous","abstract","adjective"],
["প্রয়োজনীয়","proyojoniiyo","necessary","abstract","adjective"],
["অপ্রয়োজনীয়","oproyojoniiyo","unnecessary","abstract","adjective"],
["সম্পূর্ণ","shompurno","complete / entire","abstract","adjective"],
["অসম্পূর্ণ","oshompurno","incomplete","abstract","adjective"],
["উন্নত","unnoto","developed / improved","abstract","adjective"],
["দুর্বল","durbol","weak","abstract","adjective"],
["শক্তিশালী","shoktishali","powerful / strong","abstract","adjective"],
["প্রিয়","priyo","dear / favorite","abstract","adjective"],
["বিখ্যাত","bikhyato","famous","abstract","adjective"],
["অজানা","ojana","unknown","abstract","adjective"],

// ─── POSTPOSITIONS & STRUCTURE (35) ───
["থেকে","theke","from","grammar","postposition"],
["পর্যন্ত","porjonto","until / up to","grammar","postposition"],
["জন্য","jonno","for","grammar","postposition"],
["সঙ্গে","shonge","with","grammar","postposition"],
["সাথে","shathe","with","grammar","postposition"],
["ছাড়া","chhara","without / except","grammar","postposition"],
["মতো","moto","like / as","grammar","postposition"],
["চেয়ে","cheye","than (comparison)","grammar","postposition"],
["দিকে","dike","toward","grammar","postposition"],
["মধ্যে","moddhe","among / in the middle","grammar","postposition"],
["বিষয়ে","bishoye","about / regarding","grammar","postposition"],
["পরে","pore","after","grammar","postposition"],
["আগে","age","before","grammar","postposition"],
["কাছে","kachhe","near / to (a person)","grammar","postposition"],
["উপরে","upore","on / above","grammar","postposition"],
["নিচে","niche","under / below","grammar","postposition"],
["পাশে","pashe","beside / next to","grammar","postposition"],
["ভিতরে","bhitore","inside","grammar","postposition"],
["বাইরে","baire","outside","grammar","postposition"],
["দ্বারা","dara","by (agent)","grammar","postposition"],
["প্রতি","proti","toward / per / each","grammar","postposition"],
["পর","por","after (time)","grammar","postposition"],
["আগে","age","before (time)","grammar","postposition"],
["যখন","jokhon","when","grammar","conjunction"],
["তখন","tokhon","then (at that time)","grammar","conjunction"],
["যেমন","jemon","as / like / for example","grammar","conjunction"],
["তেমন","temon","so / like that","grammar","conjunction"],
["যত","joto","as much as","grammar","conjunction"],
["তত","toto","that much","grammar","conjunction"],
["যদিও","jodiyo","although / even though","grammar","conjunction"],
["অথচ","othôcho","yet / nevertheless","grammar","conjunction"],
["সুতরাং","shutôrang","therefore","grammar","conjunction"],
["ফলে","phole","as a result","grammar","conjunction"],
["নাকি","naki","or (question)","grammar","particle"],
["তো","to","so / well (emphasis)","grammar","particle"],

// ─── HEALTH & BODY STATES (20) ───
["জ্বর","jor","fever","health","noun"],
["ব্যথা","byatha","pain","health","noun"],
["মাথাব্যথা","mathabyatha","headache","health","noun"],
["পেটব্যথা","petbyatha","stomachache","health","noun"],
["সর্দি","shordi","cold (illness)","health","noun"],
["কাশি","kashi","cough","health","noun"],
["ওষুধ","oshudh","medicine","health","noun"],
["চিকিৎসা","chikitsha","treatment","health","noun"],
["ডাক্তার","daktar","doctor","health","noun"],
["হাসপাতাল","hashpatal","hospital","health","noun"],
["রোগ","rog","disease","health","noun"],
["রোগী","rogi","patient","health","noun"],
["ইনজেকশন","injection","injection","health","noun"],
["অপারেশন","operation","operation / surgery","health","noun"],
["ট্যাবলেট","tablet","tablet / pill","health","noun"],
["এলার্জি","elarji","allergy","health","noun"],
["রক্তচাপ","roktochap","blood pressure","health","noun"],
["ডায়াবেটিস","diabetes","diabetes","health","noun"],
["টিকা","tika","vaccine","health","noun"],
["আরোগ্য","arogyo","recovery / healing","health","noun"],

// ─── TECHNOLOGY & MODERN (20) ───
["ইন্টারনেট","internet","internet","technology","noun"],
["কম্পিউটার","computer","computer","technology","noun"],
["মোবাইল","mobile","mobile phone","technology","noun"],
["ওয়েবসাইট","website","website","technology","noun"],
["ইমেইল","email","email","technology","noun"],
["সফটওয়্যার","software","software","technology","noun"],
["অ্যাপ","app","app","technology","noun"],
["ডাউনলোড","download","download","technology","noun"],
["ভিডিও","video","video","technology","noun"],
["ছবি","chhobi","photo / picture","technology","noun"],
["ক্যামেরা","camera","camera","technology","noun"],
["প্রিন্টার","printer","printer","technology","noun"],
["স্ক্রিন","screen","screen","technology","noun"],
["ব্যাটারি","battery","battery","technology","noun"],
["চার্জ","charge","charge","technology","noun"],
["পাসওয়ার্ড","password","password","technology","noun"],
["মেসেজ","message","message","technology","noun"],
["সার্চ","search","search","technology","noun"],
["নেটওয়ার্ক","network","network","technology","noun"],
["ডেটা","data","data","technology","noun"],

// ─── ACTION PHRASES (30) ───
["যেতে চাই","jete chai","I want to go","phrases","phrase"],
["আসতে পারি","ashte pari","I can come","phrases","phrase"],
["বলতে চাই","bolte chai","I want to say","phrases","phrase"],
["করতে হবে","korte hobe","have to do","phrases","phrase"],
["হতে পারে","hote pare","it could be / maybe","phrases","phrase"],
["দেখতে চাই","dekhte chai","I want to see","phrases","phrase"],
["শুনতে চাই","shunte chai","I want to listen","phrases","phrase"],
["খেতে চাই","khete chai","I want to eat","phrases","phrase"],
["পড়তে চাই","porte chai","I want to study","phrases","phrase"],
["শিখতে চাই","shikhte chai","I want to learn","phrases","phrase"],
["কী হয়েছে","ki hoyechhe","what happened","phrases","phrase"],
["কিছু হয়নি","kichhu hoyni","nothing happened","phrases","phrase"],
["চলো যাই","cholo jai","let's go","phrases","phrase"],
["এখানে আসো","ekhane esho","come here","phrases","phrase"],
["ওখানে যাও","okhane jao","go there","phrases","phrase"],
["এটা কী","eta ki","what is this","phrases","phrase"],
["কত টাকা","koto taka","how much money","phrases","phrase"],
["কোথায় যাচ্ছো","kothay jachho","where are you going","phrases","phrase"],
["কখন আসবে","kokhon ashbe","when will you come","phrases","phrase"],
["কেমন লাগছে","kemon lagchhe","how does it feel","phrases","phrase"],
["খুব ভালো","khub bhalo","very good","phrases","phrase"],
["বেশ ভালো","besh bhalo","quite good","phrases","phrase"],
["মজা পাচ্ছি","moja pachhi","I'm enjoying","phrases","phrase"],
["আমি রাজি","ami raji","I agree","phrases","phrase"],
["আমি প্রস্তুত","ami prostut","I am ready","phrases","phrase"],
["সাবধান","shabdhan","be careful","phrases","phrase"],
["তাড়াতাড়ি আসো","taratari esho","come quickly","phrases","phrase"],
["চুপ করো","chup koro","be quiet","phrases","phrase"],
["সামলে","shamle","take care / handle it","phrases","phrase"],
["ঠিক আছে","thik achhe","it's alright / okay","phrases","phrase"],

// ─── ADDITIONAL COMMON WORDS (100+) ───
["অক্টোবর","october","October","time","noun"],
["নভেম্বর","november","November","time","noun"],
["ডিসেম্বর","december","December","time","noun"],
["গত","goto","last / past","adjectives","adjective"],
["পরবর্তী","poroborti","next / subsequent","adjectives","adjective"],
["সরকারি","shorkari","government / official","adjectives","adjective"],
["বেসরকারি","beshorkari","private / non-governmental","adjectives","adjective"],
["আন্তর্জাতিক","antorjatik","international","adjectives","adjective"],
["জাতীয়","jatiyo","national","adjectives","adjective"],
["স্থানীয়","sthaniyo","local","adjectives","adjective"],
["চিঠি","chithi","letter (mail)","home","noun"],
["খাম","kham","envelope","home","noun"],
["পেন্সিল","pencil","pencil","home","noun"],
["রাবার","rabar","eraser / rubber","home","noun"],
["স্কেল","scale","ruler / scale","home","noun"],
["খাতা","khata","notebook","education","noun"],
["পাঠ","path","lesson","education","noun"],
["গৃহশিক্ষক","grihoshikkhok","tutor","professions","noun"],
["পরিচালক","porichalok","director / manager","professions","noun"],
["কর্মচারী","kormochari","employee","professions","noun"],
["মালিক","malik","owner","professions","noun"],
["সেবা","sheba","service","abstract","noun"],
["যোগাযোগ","jogajog","communication / contact","abstract","noun"],
["পরিবহন","poribohon","transportation","transport","noun"],
["ট্রাফিক","traffic","traffic","transport","noun"],
["মহাসড়ক","mohoshorok","highway","places","noun"],
["গলি","goli","alley / lane","places","noun"],
["ফুটপাত","phutpath","sidewalk","places","noun"],
["চত্বর","chottor","square / intersection","places","noun"],
["জাদুঘর","jadughor","museum","places","noun"],
["চিড়িয়াখানা","chiriyakhana","zoo","places","noun"],
["মাঝে মাঝে","majhe majhe","sometimes","adverbs","adverb"],
["সাধারণত","shadharonoto","usually","adverbs","adverb"],
["পরে","pore","later / after","adverbs","adverb"],
["আগে","age","before / earlier","adverbs","adverb"],
["তখন","tokhon","then / at that time","adverbs","adverb"],
["সঙ্গে সঙ্গে","shonge shonge","immediately","adverbs","adverb"],
["হঠাৎ","hothat","suddenly","adverbs","adverb"],
["ধীরে","dhire","slowly","adverbs","adverb"],
["আবার","abar","again","adverbs","adverb"],
["তবু","tobu","still / yet","adverbs","adverb"],
["যেন","jeno","as if / so that","grammar","conjunction"],
["পান করা","pan kora","to drink","verbs","verb"],
["চালানো","chalano","to drive / to run","verbs","verb"],
["শুনতে পাওয়া","shunte paowa","to be able to hear","verbs","verb"],
["দেখতে পাওয়া","dekhte paowa","to be able to see","verbs","verb"],
["আঁকা","aka","to draw / to paint","verbs","verb"],
["সাজানো","shajano","to decorate / arrange","verbs","verb"],
["গণনা করা","gonona kora","to calculate","verbs","verb"],
["পরিকল্পনা করা","porikolpona kora","to plan","verbs","verb"],
["প্রস্তুত করা","prostut kora","to prepare","verbs","verb"],
["অনুবাদ করা","onubad kora","to translate","verbs","verb"],
["ব্যাখ্যা করা","byakhya kora","to explain","verbs","verb"],
["সম্মত হওয়া","shommoto howa","to agree / to consent","verbs","verb"],
["প্রতিবাদ করা","protibad kora","to protest","verbs","verb"],
["উদযাপন করা","udjapon kora","to celebrate","verbs","verb"],
["হাততালি দেওয়া","hattali deowa","to clap / applaud","verbs","verb"],
["তালা দেওয়া","tala deowa","to lock","verbs","verb"],
["পরিচয়","porichoy","introduction / identity","abstract","noun"],
["সম্পর্ক","shomporko","relationship","abstract","noun"],
["বিশ্বাস","bishshash","belief / trust / faith","abstract","noun"],
["অনুমতি","onumoti","permission","abstract","noun"],
["নিমন্ত্রণ","nimontron","invitation","abstract","noun"],
["উপহার","upohar","gift / present","abstract","noun"],
["পুরস্কার","puroshkar","prize / award","abstract","noun"],
["শাস্তি","shasti","punishment","abstract","noun"],
["কারাগার","karagar","prison / jail","places","noun"],
["আদালত","adalot","court (legal)","places","noun"],
["পতাকা","potaka","flag","abstract","noun"],
["মানচিত্র","manchitro","map","abstract","noun"],
["ইউনিফর্ম","uniform","uniform","clothing","noun"],
["কোট","kot","coat","clothing","noun"],
["মোজা","moja","socks","clothing","noun"],
["গামছা","gamchha","thin towel (traditional)","clothing","noun"],
["হীরা","hira","diamond","abstract","noun"],
["সোনা","shona","gold","abstract","noun"],
["রুপা","rupa","silver","abstract","noun"],
["তামা","tama","copper","abstract","noun"],
["লোহা","loha","iron","abstract","noun"],
["বাঁশ","bash","bamboo","nature","noun"],
["ধান","dhan","paddy / rice plant","nature","noun"],
["পাট","pat","jute","nature","noun"],
["চা বাগান","cha bagan","tea garden","nature","noun"],
["খোলা মাঠ","khola math","open field","nature","noun"],
["ভূমিকম্প","bhumikampo","earthquake","nature","noun"],
["বন্যা","bonnya","flood","nature","noun"],
["খরা","khora","drought","nature","noun"],
["ঘূর্ণিঝড়","ghurnijhor","cyclone","nature","noun"],
["তুষারপাত","tusharpat","snowfall","nature","noun"],
["কুয়াশা","kuyasha","fog / mist","nature","noun"],
["রংধনু","rongdhonu","rainbow","nature","noun"],
["ভোর","bhor","dawn","time","noun"],
["গোধূলি","godhuli","twilight","time","noun"],
["মধ্যরাত","moddhorat","midnight","time","noun"],
["শতাব্দী","shotabdi","century","time","noun"],
["দশক","doshok","decade","time","noun"],
["কচ্ছপ","kochchhop","turtle / tortoise","animals","noun"],
["কুমির","kumir","crocodile","animals","noun"],
["পেঁচা","pecha","owl","animals","noun"],
["তোতা","tota","parrot","animals","noun"],
["কবুতর","kobutor","pigeon","animals","noun"],
["মাকড়সা","makorsha","spider","animals","noun"],
["জোনাকি","jonaki","firefly","animals","noun"],
["চিংড়ি","chingri","shrimp / prawn","food","noun"],
["সরিষা","shorisha","mustard","food","noun"],
["পালং শাক","palong shak","spinach","food","noun"],
["বেগুন","begun","eggplant / brinjal","food","noun"],
["ফুলকপি","phulkopi","cauliflower","food","noun"],
["বাঁধাকপি","badhakopi","cabbage","food","noun"],
["মূলা","mula","radish","food","noun"],
["লাউ","lau","bottle gourd","food","noun"],
];

// Category metadata
const VOCAB_CATEGORIES = {
  "pronouns":    { title:"Pronouns & Questions", icon:"👤", color:"#ce82ff" },
  "numbers":     { title:"Numbers", icon:"🔢", color:"#49c0f8" },
  "family":      { title:"Family & People", icon:"👪", color:"#ff9600" },
  "body":        { title:"Body & Health", icon:"🦴", color:"#ff6b6b" },
  "food":        { title:"Food & Drink", icon:"🍚", color:"#ffc800" },
  "animals":     { title:"Animals", icon:"🐅", color:"#58cc02" },
  "colors":      { title:"Colors", icon:"🎨", color:"#ff9600" },
  "time":        { title:"Time & Calendar", icon:"🕐", color:"#49c0f8" },
  "nature":      { title:"Nature & Weather", icon:"🌳", color:"#58cc02" },
  "home":        { title:"Home & Objects", icon:"🏠", color:"#ce82ff" },
  "places":      { title:"Places", icon:"📍", color:"#ff6b6b" },
  "verbs":       { title:"Common Verbs", icon:"🏃", color:"#49c0f8" },
  "adjectives":  { title:"Adjectives", icon:"📐", color:"#ffc800" },
  "adverbs":     { title:"Adverbs & Connectors", icon:"🔗", color:"#ce82ff" },
  "expressions": { title:"Greetings & Phrases", icon:"🗣️", color:"#58cc02" },
  "professions": { title:"Professions", icon:"💼", color:"#ff9600" },
  "transport":   { title:"Transport", icon:"🚗", color:"#49c0f8" },
  "clothing":    { title:"Clothing & Accessories", icon:"👕", color:"#ff6b6b" },
  "emotions":    { title:"Emotions & Feelings", icon:"❤️", color:"#ff6b6b" },
  "education":   { title:"Education & Work", icon:"📚", color:"#ffc800" },
  "society":     { title:"Society & Religion", icon:"🏛️", color:"#ce82ff" },
  "abstract":    { title:"Abstract & General", icon:"💡", color:"#49c0f8" },
  "grammar":     { title:"Grammar Words", icon:"📖", color:"#ff9600" },
  "health":      { title:"Health & Medicine", icon:"🏥", color:"#ff6b6b" },
  "technology":  { title:"Technology", icon:"💻", color:"#49c0f8" },
  "phrases":     { title:"Useful Phrases", icon:"💬", color:"#58cc02" },
};
