// Bengali Vocabulary — 4,399 most common words
// Source schema: [lemma, roman, english, category, pos, example, senseId?, related?]
// Runtime schema: { lemma, roman, english, category, pos, example, senseId, related, freqRank }


const VOCAB_DATA_RAW = [
// Pack 0 — top curriculum words (lazy packs 1-3 loaded at runtime)
// ─── EXPRESSIONS ───
["না","na","no / not","expressions","expression","না, আমি পারব না। (na, ami parbo na — No, I cannot.)"],
// ─── PRONOUNS ───
["এই","ei","this","pronouns","pronoun","এই বাড়িটা সুন্দর। (ei barita shundor — This house is beautiful.)"],
["তার","tar","his / her / its","pronouns","pronoun","তার বই খুবই সুন্দর। (tar boi khuboi sundar — His/her book is very beautiful.)"],
["যে","je","that / which / who","pronouns","pronoun","যে ছেলেটি এসেছে সে খুব বুদ্ধিমান। (je cheletí esechhe se khub budhiman — The boy who came is very intelligent.)"],
["আমি","ami","I / me","pronouns","pronoun","আমি বাংলা শিখছি। (ami bangla shikhchhi — I am learning Bengali.)","",[{"ref":"আমার","type":"derived"},{"ref":"আমরা","type":"derived"},{"ref":"আমাদের","type":"compound"}]],
// ─── NUMBERS ───
["একটি","ekti","a / one","numbers","number","আমার একটি বিড়াল আছে। (amar ekti biral ache — I have a cat.)","",[{"ref":"এক","type":"derived"},{"ref":"একটা","type":"synonym"}]],
// ─── VERBS ───
["করে","kore","does / makes","verbs","verb","সে প্রতিদিন কাজ করে। (se protidine kaj kore — She does work every day.)","",[{"ref":"করা","type":"derived"},{"ref":"করতে","type":"derived"},{"ref":"কাজ","type":"compound"}]],
["করা","kora","to do / to make","verbs","verb","তুমি কী করছ? (tumi ki korchho — What are you doing?)","",[{"ref":"করে","type":"derived"},{"ref":"করতে","type":"derived"},{"ref":"কাজ","type":"compound"}]],
["করতে","korte","to do / to make","verbs","verb","আমি এটা করতে চাই। (ami eta korte chai — I want to do this.)","",[{"ref":"করা","type":"derived"},{"ref":"করে","type":"derived"}]],
["হবে","hobe","will be / shall be","verbs","verb","আগামীকাল ছুটির দিন হবে। (agamikal chutir din hobe — Tomorrow will be a holiday.)","",[{"ref":"হতে","type":"derived"},{"ref":"হচ্ছে","type":"derived"},{"ref":"হয়ে","type":"derived"}]],
// ─── ADVERBS ───
["এবং","ebong","and","adverbs","conjunction","সে এবং আমি বন্ধু। (she ebong ami bondhu — She and I are friends.)"],
["আর","ar","and / more / else","adverbs","particle","আর কিছু লাগবে? (ar kichhu lagbe? — Do you need anything more?)"],
// ─── GRAMMAR ───
["ও","o","and","grammar","conjunction","রহিম ও করিম আসবেন। (rohim o korim asben — Rohim and Korim will come.)"],
["থেকে","theke","from","grammar","postposition","ঢাকা থেকে চট্টগ্রাম দূরে। (Dhaka theke Chattogram dure — Chittagong is far from Dhaka.)"],
["জন্য","jonno","for","grammar","postposition","তোমার জন্য খাবার এনেছি। (tomar jonno khabar enechhi — I brought food for you.)"],
["এর","er","of / 's","grammar","particle","বাড়ির দরজা লাল। (barirer dorja lal — The door of the house is red.)"],
["এ","e","in / at / on","grammar","preposition","ঢাকায় আমাদের বাড়ি আছে। (dhakay amader bari ache — We have a house in Dhaka.)"],
// ─── PRONOUNS ───
["আমার","amar","my","pronouns","pronoun","আমার নাম করিম। (amar nam korim — My name is Korim.)"],
["তিনি","tini","he / she (formal)","pronouns","pronoun","তিনি খুব ভালো মানুষ। (tini khub bhalo manush — He/she is a very good person.)"],
["কিছু","kichhu","something / some","pronouns","pronoun","আমি কিছু খাব না। (ami kichhu khabo na — I will not eat anything.)"],
["আমাদের","amader","our / ours","pronouns","pronoun","আমাদের দেশ খুবই সুন্দর। (amader desh khuboi sundar — Our country is very beautiful.)"],
["আমরা","amra","we","pronouns","pronoun","আমরা একসাথে যাব। (amra ekshate jabo — We will go together.)"],
["তাদের","tader","their / theirs","pronouns","pronoun","তাদের বাড়িটি খুব বড়। (tader bariți khub boro — Their house is very big.)"],
["তারা","tara","they","pronouns","pronoun","তারা বাজারে গেছে। (tara bajare geche — They have gone to the market.)"],
["যা","ja","which / that","pronouns","pronoun","যা বলেছ তা সত্য। (ja bolechchh ta sattya — What you said is true.)"],
["সে","she","he / she / they (singular)","pronouns","pronoun","সে আমাদের শিক্ষক। (she amader shikkhok — He/she is our teacher.)"],
["সব","shob","all / everything","pronouns","pronoun","সব ঠিক আছে। (shob thik achhe — Everything is alright.)"],
["আপনার","apnar","your (formal)","pronouns","pronoun","আপনার নাম কী? (apnar nam ki — What is your name?)"],
["তা","ta","that / it","pronouns","pronoun","এটি খুবই গুরুত্বপূর্ণ তা আমি জানি। (eți khuboi guruttvopurn ta ami jani — I know that this is very important.)"],
["এটা","eta","this (thing)","pronouns","pronoun","এটা কী? (eta ki — What is this?)"],
["সেই","sei","that / the same","pronouns","pronoun","সেই মেয়েটি আমার বন্ধু। (sei meytî amar bondhu — That girl is my friend.)"],
// ─── NUMBERS ───
["এক","ek","one","numbers","number","টেবিলে একটি বই আছে। (tebile ekti boi achhe — There is one book on the table.)","",[{"ref":"একটি","type":"derived"},{"ref":"একটা","type":"derived"},{"ref":"একজন","type":"compound"}]],
["একটা","ekta","a / one","numbers","number","একটা পেন্সিল কিনো। (ekta pencil kino — Buy a pencil.)","",[{"ref":"একটি","type":"synonym"},{"ref":"এক","type":"derived"}]],
["একজন","ekjon","one person / a person","numbers","number","একজন শিক্ষক এসেছেন। (ekjon shikkhok esechhen — A teacher has come.)"],
["নয়","noy","nine","numbers","number","সে নয় বছর আগে এসেছিল। (she noy bochor age eshechhilo — She came nine years ago.)"],
// ─── VERBS ───
["হয়েছে","hoyechhe","has happened / has been","verbs","verb","অনেক কিছু পরিবর্তন হয়েছে। (onek kichu pariborten hoyechhe — Many things have changed.)"],
["হয়ে","hoye","becoming / by","verbs","verb","সে একজন ডাক্তার হয়ে গেছে। (she ekjon daktar hoye gechhe — He has become a doctor.)"],
["ছিল","chhil","was / were","verbs","verb","সে গতকাল ঘরে ছিল। (she gotkal ghore chhilo — He was home yesterday.)"],
["যায়","jay","goes / goes away","verbs","verb","প্রতিদিন সকালে সে স্কুলে যায়। (protidine sakale she schoole jay — He goes to school every morning.)"],
["হচ্ছে","hochhe","is happening / is being","verbs","verb","বৃষ্টি হচ্ছে। (brishti hochhe — It is raining.)"],
["করেন","koren","do / make (formal)","verbs","verb","আপনি কী করেন? (apni ki koren — What do you do?)"],
["করার","korar","of doing / of making","verbs","verb","কাজ করার জন্য সময় দরকার। (kaj korar jonno somoy dorkar — Time is needed for doing work.)"],
["আছে","ache","is / are / have","verbs","verb","আমাদের একটি বাগান আছে। (amader ekti bagan ache — We have a garden.)"],
["পারে","pare","can / is able to","verbs","verb","সে এটি করতে পারে। (she eți korte pare — He can do this.)"],
["নেই","nei","is not / are not","verbs","verb","আমার কাছে টাকা নেই। (amar kachhe taka nei — I don't have money.)"],
["শুরু","shuru","start / beginning","abstract","noun","তিনি কাজ শুরু করেছেন। (tini kaj shuru korchhen — He has started working.)"],
["বলে","bole","says / told / means","verbs","verb","সে কী বলে? (she ki bole — What does she say?)"],
["হতে","hote","to be / to become","verbs","verb","তাকে ডাক্তার হতে হবে। (take daktar hote hobe — He has to become a doctor.)"],
// ─── ADJECTIVES ───
["অনেক","onek","many / much / a lot","adjectives","adjective","আমাদের অনেক কাজ আছে। (amader onek kaj achhe — We have a lot of work.)"],
// ─── TIME ───
["সময়","shomoy","time","time","noun","এখন সময় নেই। (ekhon shomoy nei — There is no time now.)"],
["এখন","ekhon","now","time","adverb","এখন বাড়ি যাও। (ekhon bari jao — Go home now.)"],
["বছর","bochor","year","time","noun","নতুন বছর শুরু হলো। (notun bochor shuru holo — The new year has begun.)"],
// ─── ADVERBS ───
["কিন্তু","kintu","but","adverbs","conjunction","চাই, কিন্তু পারছি না। (chai, kintu parchi na — I want to, but I can't.)"],
["যদি","jodi","if","adverbs","conjunction","যদি আসো তাহলে জানাও। (jodi asho tahole janao — If you come, let me know.)"],
// ─── EDUCATION ───
["কাজ","kaj","work / job","education","noun","আমার আজ অনেক কাজ আছে। (amar aj onek kaj achhe — I have a lot of work today.)"],
// ─── GRAMMAR ───
["নিয়ে","niye","with / about / for","grammar","preposition","সে তার ছেলেকে নিয়ে স্কুলে যায়। (she tar chhelek niye schoole jay — She takes her son to school.)"],
["সাথে","shathe","with","grammar","postposition","বন্ধুর সাথে বেড়াতে গেলাম। (bondhur shathe beraate gelam — I went out with a friend.)"],
["কি","ki","what / is it","grammar","particle","তুমি কি আসবে? (tumi ki asbe — Will you come?)"],
["কোন","kon","which / any","grammar","pronoun","কোন বই পড়ছেন? (kon boi porchhen — Which book are you reading?)"],
["মধ্যে","moddhe","among / in the middle","grammar","postposition","ছাত্রদের মধ্যে সে সেরা। (chhhathrder moddhe she shera — Among the students, she is the best.)"],
["দিয়ে","diye","with / by / giving","grammar","preposition","সে পেন দিয়ে লিখছে। (she pen diye likhchhe — She is writing with a pen.)"],
["বা","ba","or","grammar","conjunction","চা বা কফি? (cha ba kopi — Tea or coffee?)"],
["পর","por","after (time)","grammar","postposition","বৃষ্টির পর রোদ উঠল। (brishhtir por rod uthlo — After the rain, the sun came out.)"],
// ─── ABSTRACT ───
["কথা","kotha","word / speech / matter","abstract","noun","তার কথা শুনে আমি অবাক হলাম। (tar kotha shune ami obak holam — Hearing his words, I was surprised.)"],
// ─── GRAMMAR ───
["কাছে","kachhe","near / to (a person)","grammar","postposition","ডাক্তারের কাছে যাও। (daktarer kachhe jao — Go to the doctor.)"],
// ─── ABSTRACT ───
["মনে","mone","in mind / think / remember","abstract","adverb","তোমার মনে আছে কি? (tomak mone ache ki — Do you remember?)"],
// ─── EXPRESSIONS ───
["ঘোষণা","ghoshnā","announcement / declaration","expressions","noun","প্রধানমন্ত্রী একটি গুরুত্বপূর্ণ ঘোষণা করেছেন। (prodhānmontri ekti guruttopoorno ghoshnā korechen — The Prime Minister made an important announcement.)"],
["অভিযোগ","obhiyog","complaint / accusation","expressions","noun","তিনি একটি গুরুতর অভিযোগ করেছেন। (tini ekti guruter obhiyog korechen — He made a serious complaint.)"],
// ─── PRONOUNS ───
["তাকে","take","him / her / it","pronouns","pronoun","তাকে ডাকো। (take dako — Call him/her.)"],
["আপনি","apni","you (formal)","pronouns","pronoun","আপনি কি ঢাকায় থাকেন? (apni ki dhakay thaken — Do you live in Dhaka?)"],
["কে","ke","who","pronouns","pronoun","সে কে? (she ke — Who is he/she?)"],
["কেউ","keu","someone","pronouns","pronoun","কেউ দরজায় আছে। (keu dorjay achhe — Someone is at the door.)"],
["এটি","eti","this / it","pronouns","pronoun","এটি আমার পেন। (eți amar pen — This is my pen.)"],
["কেন","keno","why","pronouns","pronoun","তুমি কেন কাঁদছ? (tumi keno kandcho — Why are you crying?)"],
["তুমি","tumi","you (informal)","pronouns","pronoun","তুমি কোথায় যাচ্ছ? (tumi kothay jaccho — Where are you going?)"],
["তোমার","tomar","your","pronouns","pronoun","এটি তোমার বই। (eti tomar boi — This is your book.)"],
["কোনো","kono","any / some","pronouns","pronoun","কোনো সমস্যা নেই। (kono somossha nei — There is no problem.)"],
["নিজের","nijer","of oneself / own","pronouns","pronoun","এটি নিজের সিদ্ধান্ত। (eti nijer siddhanto — This is one's own decision.)"],
["তাঁর","tar","his / her / their","pronouns","pronoun","তাঁর নাম রহিম। (tar nam rohim — His name is Rahim.)"],
["যার","jar","whose / which","pronouns","pronoun","যার বই এটি? (jar boi eti — Whose book is this?)"],
["যারা","jara","who (plural)","pronouns","pronoun","যারা আসবে তারা খাবে। (jara asbe tara khabe — Those who come will eat.)"],
["সবাই","sbai","everyone / all","pronouns","pronoun","সবাই খুশি। (sbai khushi — Everyone is happy.)"],
["আমাকে","amake","me","pronouns","pronoun","তুমি আমাকে সাহায্য করবে। (tumi amake sahayyo korbe — You will help me.)"],
["কী","ki","what","pronouns","pronoun","তুমি কী চাও? (tumi ki chao — What do you want?)"],
// ─── NUMBERS ───
["দুই","dui","two","numbers","number","আমার দুটো হাত আছে। (amar duto hat achhe — I have two hands.)"],
["হাজার","hajar","thousand","numbers","number","সে হাজার টাকা হারিয়ে ফেলেছে। (she hajar taka hariye pheleche — She lost a thousand takas.)"],
["তিন","tin","three","numbers","number","সে তিনটা আম খেল। (she tinta am khelo — She ate three mangoes.)"],
// ─── VERBS ───
["রয়েছে","royche","is / exists / is there","verbs","verb","এখানে অনেক ফুল রয়েছে। (ekhane onek phul royche — There are many flowers here.)"],
["করেছে","korechhe","has done / has made","verbs","verb","সে কাজ করেছে। (she kaj korechhe — He has done the work.)"],
["করেছেন","korechen","have done / have made (formal)","verbs","verb","আপনি কী করেছেন? (apni ki korechen — What have you done?)"],
["দেখা","dekha","to see / to look","verbs","verb","আমি তোমাকে দেখি। (ami tomake dekhi — I see you.)"],
["গেছে","gechhe","has gone / went","verbs","verb","সে বাড়িতে গেছে। (she bariте gechhe — She has gone home.)"],
["থাকে","thake","stays / remains / keeps","verbs","verb","সে ঘরে থাকে। (she ghore thake — He stays at home.)"],
["দিতে","dite","to give","verbs","verb","আমাকে একটি বই দিতে পারবেন? (amake ekti boi dite parben — Can you give me a book?)"],
["করছে","korchhe","is doing / is making","verbs","verb","সে এখন কাজ করছে। (she ekhon kaj korchhe — He is doing work now.)"],
["করবে","korbe","will do / will make","verbs","verb","আগামীকাল সে পড়াশোনা করবে। (agamikal she porasona korbe — He will study tomorrow.)"],
["করি","kori","do / make","verbs","verb","আমি কাজ করি। (ami kaj kori — I do work.)"],
["যাবে","jabe","will go","verbs","verb","সে আগামীকাল যাবে। (she agamikalal jabe — He will go tomorrow.)"],
["ব্যবহার","byabhar","use / usage","verbs","noun","এই যন্ত্রের ব্যবহার সহজ। (ei jontrer byabhar shohoj — The use of this instrument is easy.)"],
["ধরে","dhore","holding / catching / assuming","verbs","verb","তিনি হাত ধরে চলেছেন। (tin hat dhore cholechhen — He is walking while holding hands.)"],
["হলো","holo","is / was / became","verbs","verb","এটি একটি ভাল দিন হলো। (eti ekti bhal din holo — It was a good day.)"],
["তৈরি","taiiri","made / created / prepared","verbs","verb","আমরা একটি পরিকল্পনা তৈরি করেছি। (amra ekti porikolpna tairi korechi — We made a plan.)"],
["যাচ্ছে","jachhche","is going","verbs","verb","সে স্কুলে যাচ্ছে। (she shkuley jachhche — She is going to school.)"],
["চাই","chai","want / desire","verbs","verb","আমি পড়তে চাই। (ami porhte chai — I want to study.)"],
["দেয়","dey","gives","verbs","verb","সে সাহায্য দেয়। (she sahayyo dey — He helps.)"],
["পাওয়া","paowa","to get / to receive","verbs","verb","চিঠি পাওয়া গেছে। (chithi paoa geche — The letter has been received.)"],
["হলে","hole","if / becomes","verbs","verb","যদি বৃষ্টি হলে খেলা বন্ধ হবে। (jodi brishti hole khela bondh hobe — If it rains, the game will be cancelled.)"],
["চলে","chole","runs / works / functions","verbs","verb","গাড়ি ভালোভাবে চলে। (gari bhalovabe chale — The car runs well.)"],
["ছিলেন","chilen","were","verbs","verb","তারা সেখানে ছিলেন। (tara shekhanay chilen — They were there.)"],
["দেখতে","dekhte","to see / to look","verbs","verb","আমি নাটক দেখতে যেতে চাই। (ami natak dekhte jete chai — I want to go see a play.)"],
// ─── FAMILY ───
["মানুষ","manush","person / human","family","noun","সে খুব ভালো মানুষ। (she khub bhalo manush — She is a very good person.)"],
["মা","ma","mother","family","noun","আমার মা রান্না করছেন। (amar ma ranna korchhen — My mother is cooking.)"],
["ভাই","bhai","brother","family","noun","আমার ভাই স্কুলে যায়। (amar bhai skule jay — My brother goes to school.)"],
// ─── ADJECTIVES ───
["নতুন","notun","new","adjectives","adjective","আমার নতুন জুতো কিনলাম। (amar notun juto kinalm — I bought new shoes.)"],
["ভালো","bhalo","good","adjectives","adjective","সে একজন ভালো মানুষ। (she ekjon bhalo manush — He is a good person.)"],
["প্রথম","prothom","first","adjectives","adjective","সে প্রথম হয়েছে। (she prothom hoyeche — She came first.)"],
["এমন","eman","such / like this / this kind of","adjectives","adjective","এমন কথা বলবেন না। (eman kotha bolben na — Don't say such things.)"],
["বেশি","beshi","more / much","adjectives","adjective","বেশি খেলে শরীর খারাপ হয়। (beshi khele shorir kharap hoy — Eating too much makes you sick.)"],
["জাতীয়","jatiyo","national","adjectives","adjective","জাতীয় পতাকা উড়ছে। (jatiyo potaka urchhe — The national flag is flying.)"],
["বিভিন্ন","bibhinn","various / different","adjectives","adjective","বিভিন্ন ধরনের ফুল এখানে আছে। (bibhinn dhoner phul ekhane ache — There are various types of flowers here.)"],
["শেষ","shesh","last / end","adjectives","adjective","শেষ বাস চলে গেছে। (shesh bash chole geche — The last bus has gone.)"],
["বড়","boro","big / elder","adjectives","adjective","এই বাড়িটা অনেক বড়। (ei barita onek boro — This house is very big.)"],
["প্রধান","pradhan","main / principal / chief","adjectives","adjective","এটি প্রধান কারণ। (eti pradhan karon — This is the main reason.)"],
["গত","goto","last / past","adjectives","adjective","গত সপ্তাহে ঢাকা গিয়েছিলাম। (goto shoptahe Dhaka giyechhilam — I went to Dhaka last week.)"],
["ঠিক","thik","right / correct","adjectives","adjective","ঠিক কথা বলো। (thik kotha bolo — Speak the right thing.)"],
["অন্য","onno","other / another","adjectives","adjective","অন্য কোনো উপায় আছে কি? (onno kono upay ache ki — Is there any other way?)"],
["বিশেষ","bishesh","special","adjectives","adjective","আজকে একটা বিশেষ দিন। (ajke ekta bisesh din — Today is a special day.)"],
["একই","eki","same","adjectives","adjective","আমরা একই স্কুলে পড়ি। (amra eki skule pori — We study at the same school.)"],
["ভাল","bhal","good / well","adjectives","adjective","এটি একটি ভাল বই। (eti ekti bhal boi — This is a good book.)"],
["আন্তর্জাতিক","antorjatik","international","adjectives","adjective","এটি একটি আন্তর্জাতিক সম্মেলন। (eta ekti antorjatik shommhelon — This is an international conference.)"],
["সামনে","shamne","in front / ahead","adverbs","adverb","স্কুল সামনে আছে। (school shamne achhe — The school is ahead.)"],
["সাধারণ","shadharon","ordinary / common","adjectives","adjective","এটা একটা সাধারণ ব্যাপার। (eta ekta shadharon byapar — This is an ordinary matter.)"],
["ছোট","choto","small / little","adjectives","adjective","এটি একটি ছোট বাড়ি। (eti ekti choto bāri — This is a small house.)"],
// ─── TIME ───
["দিন","din","day","time","noun","আজ ভালো দিন। (aj bhalo din — Today is a good day.)"],
["আজ","aj","today","time","adverb","আজ আকাশ পরিষ্কার। (aj akash porishkar — Today the sky is clear.)"],
["সালে","sale","in the year","time","noun","২০২০ সালে এটি ঘটেছে। (2020 sale eti ghoteche — This happened in 2020.)"],
["সালের","saler","of the year","time","noun","এই সালের শুরু খুবই ভাল ছিল। (ei saler shuru khuboei bhal chilo — The beginning of this year was very good.)"],
["বছরের","bochhorer","of the year","time","noun","এই বছরের শেষে মিলিত হব। (ei bochhorer sheshe mili hob — We will meet at the end of this year.)"],
// ─── HOME ───
["টাকা","taka","money","home","noun","টাকা সঠিকভাবে খরচ করো। (taka shothikbhabe khoroch koro — Spend money wisely.)"],
["ছবি","chhobi","picture / photo","home","noun","সে সুন্দর ছবি আঁকে। (she shundor chhobi ake — She draws beautiful pictures.)"],
// ─── BODY ───
["হাতে","hāte","in hand / in possession","body","noun","আমার হাতে একটি বই আছে। (āmār hāte ekti boi āche — I have a book in my hand.)"],
// ─── PLACES ───
["দেশের","desher","of the country","places","noun","দেশের উন্নয়ন সবার লক্ষ্য। (desher unnoyom sbar lokkhyo — The country's development is everyone's goal.)"],
["জেলা","jelā","district","places","noun","আমি ঢাকা জেলায় থাকি। (āmi ḍhākā jelāy thāki — I live in Dhaka district.)"],
["দেশে","deshe","in the country / in the nation","places","noun","দেশে অনেক সমস্যা আছে। (deshe onek somosshā āche — There are many problems in the country.)"],
["দেশ","desh","country","places","noun","আমার দেশ সুন্দর। (amar desh shundor — My country is beautiful.)"],
// ─── ADVERBS ───
["তবে","tobe","then / however","adverbs","conjunction","ভালো, তবে আরো চেষ্টা করো। (bhalo, tobe aro cheshta koro — Good, but try more.)"],
["আগে","age","before / earlier","adverbs","adverb","ঘুমানোর আগে বই পড়ো। (ghumanoar age boi poro — Read a book before sleeping.)"],
["তাই","tai","so / therefore","adverbs","conjunction","বৃষ্টি হচ্ছে, তাই বাইরে যাইনি। (brishti hochhe, tai baire jaini — It's raining, so I didn't go out.)"],
["খুব","khub","very","adverbs","adverb","সে খুব ভালো গান গায়। (she khub bhalo gan gay — She sings very well.)"],
["এখানে","ekhane","here","adverbs","adverb","এখানে বসো। (ekhane bosho — Sit here.)"],
["পরে","pore","later / after","adverbs","adverb","খাওয়ার পরে বিশ্রাম নাও। (khawar pore bishram nao — Rest after eating.)"],
["উপর","upar","on / above / upper","adverbs","adverb","টেবিলের উপর বই রয়েছে। (tebil'er upar boi royeche — There are books on the table.)"],
["আবার","abar","again","adverbs","adverb","তুমি আবার এসো। (tumi abar esho — Come again.)"],
["কারণ","karon","because / reason","adverbs","conjunction","সে আসেনি, কারণ জানি না। (she asheni, karon jani na — She didn't come, I don't know the reason.)"],
["তখন","tokhon","then / at that time","adverbs","adverb","তখন আমি ছোট ছিলাম। (tokhon ami chhoto chhilam — I was small then.)"],
["প্রায়","pray","almost / often","adverbs","adverb","সে প্রায় প্রতিদিন আসে। (she pray protidin ashe — He comes almost every day.)"],
["শুধু","shudhu","only / just","adverbs","adverb","শুধু তুমিই পারবে। (shudhu tumii parbe — Only you can do it.)"],
["তাহলে","tahole","then / in that case","adverbs","conjunction","সে এলে তাহলে কথা বলব। (she ele tahole kotha bolbo — If he comes, then I'll talk.)"],
["আরো","aro","more","adverbs","adverb","আরো বই দাও। (aro boi dao — Give me more books.)"],
// ─── EDUCATION ───
["বাংলা","bangla","Bengali","education","noun","বাংলা পৃথিবীর সুন্দর ভাষা। (bangla prithibir shundor bhasha — Bengali is a beautiful language of the world.)"],
["উত্তর","uttor","answer / north","education","noun","সে সব প্রশ্নের উত্তর দিল। (she shob proshner uttor dilo — She answered all the questions.)"],
// ─── PROFESSIONS ───
["পুলিশ","pulish","police","professions","noun","পুলিশ চোরকে ধরল। (polish chorke dhorlo — The police caught the thief.)"],
// ─── GRAMMAR ───
["হিসেবে","hisebe","as / in the capacity of","grammar","preposition","তিনি শিক্ষক হিসেবে কাজ করছেন। (tini shikkhok hisebe kaj korchhen — He is working as a teacher.)"],
["যখন","jokhon","when","grammar","conjunction","যখন ডাকবে, আসবো। (jokhon dakbe, ashbo — When you call, I will come.)"],
["তো","to","so / well (emphasis)","grammar","particle","তুমি তো জানোই। (tumi to janoi — You already know, don't you.)"],
["পর্যন্ত","porjonto","until / up to","grammar","postposition","সকাল থেকে রাত পর্যন্ত কাজ করি। (shokal theke rat porjonto kaj kori — I work from morning until night.)"],
["দিকে","dike","toward","grammar","postposition","সে বাড়ির দিকে হাঁটছে। (she barir dike hatchhe — She is walking toward home.)"],
["মতো","moto","like / as","grammar","postposition","সে পাখির মতো গান গায়। (she pakhir moto gan gay — She sings like a bird.)"],
["প্রতি","proti","toward / per / each","grammar","postposition","প্রতি মানুষের প্রতি সদয় হও। (proti manusher proti shodoy hao — Be kind to every person.)"],
["সঙ্গে","shonge","with","grammar","postposition","আমি তোমার সঙ্গে যাবো। (ami tomar shonge jabo — I will go with you.)"],
// ─── HEALTH ───
["আল","āl","pus / suppuration","health","noun","ক্ষতে আল জমেছে। (khote āl jomeche — Pus has accumulated in the wound.)"],
// ─── TECHNOLOGY ───
["ভিডিও","video","video","technology","noun","সে একটা ভিডিও পাঠাল। (she ekta video pathalo — She sent a video.)"],
// ─── SOCIETY ───
["সরকার","shorkar","government","society","noun","সরকার নতুন আইন করেছে। (shorkar notun ain koreche — The government has made a new law.)"],
["জীবন","jibon","life","society","noun","জীবন সুন্দর। (jibon shundor — Life is beautiful.)"],
// ─── ABSTRACT ───
["নাম","nam","name","abstract","noun","তোমার নাম কী? (tomar nam ki — What is your name?)"],
// ─── VERBS ───
["বলা","bola","to say / to tell","verbs","verb","সত্য কথা বলা ভালো। (sotty kotha bola bhalo — It is good to speak the truth.)"],
["করুন","korun","do / make (formal/imperative)","verbs","verb","এটি করুন। (eti korun — Do this.)"],
["পড়ে","pore","falls / happens / occurs","verbs","verb","বৃষ্টি পড়ে গেছে। (brishti pore geche — It has rained.)"],
["হয়েছিল","hoechilos","had happened / had been","verbs","verb","এটি আগে হয়েছিল। (eti age hoechilos — This had happened before.)"],
["অনুষ্ঠিত","anushthito","held / conducted / organized","verbs","verb","অনুষ্ঠানটি গতকাল অনুষ্ঠিত হয়েছিল। (anusthanto gatkal anushthito hoechilos — The event was held yesterday.)"],
["দেখে","dekhe","seeing / watching / looking at","verbs","verb","তিনি আমাকে দেখে হাসলেন। (tin amake dekhe haslen — He laughed upon seeing me.)"],
["দেওয়া","deowa","to give","verbs","verb","আমাকে একটু সময় দাও। (amake ektu shomoy dao — Give me a little time.)"],
["যেতে","jete","to go","verbs","verb","আমাকে যেতে হবে। (amake jete hobe — I have to go.)"],
["হওয়ার","howar","of being / to become","verbs","verb","ভালো হওয়ার জন্য ওষুধ খান। (bhālo howar jonno oshudh khān — Take medicine to get better.)"],
["করবেন","korben","will do / shall do","verbs","verb","আগামীকাল আপনি কাজ করবেন। (agamikal apni kaj korben — You will do the work tomorrow.)"],
["দেয়া","deoyā","to give / given","verbs","verb","তাকে একটি উপহার দেওয়া হয়েছে। (tāke ekti uphār deoyā hoyeche — He was given a gift.)"],
["দেখুন","dekhun","see / look / watch","verbs","verb","দেখুন এই ছবিটি কতো সুন্দর! (dekhun ei chhobit koto sunder — Look at how beautiful this picture is!)"],
["পারেন","pāren","can / able to / capable of","verbs","verb","তিনি এটি করতে পারেন। (tini eti korte pāren — He can do this.)"],
["নিতে","nite","to take / taking","verbs","verb","আমি দোকান থেকে জিনিস নিতে যাচ্ছি। (āmi dokān theke jinish nite yāchchi — I am going to take things from the shop.)"],
["গিয়ে","giye","going / went / after going","verbs","verb","সে বাজারে গিয়ে জিনিস কিনেছে। (she bāzāre giye jinish kineche — She went to the market and bought things.)"],
["দিয়েছে","diyeche","has given / gave","verbs","verb","সে আমাকে একটি বই দিয়েছে। (she amake ekti boi diyechhe — He has given me a book.)"],
["এসে","ese","coming / came","verbs","verb","সে এসে আমার সাথে কথা বলেছে। (she ese āmār sāthe kothā boleche — She came and talked to me.)"],
["বলতে","bolte","to say / speaking","verbs","verb","আমাকে সত্য কথা বলতে হবে। (āmāke sotty kothā bolte hobe — I have to tell the truth.)"],
// ─── ADJECTIVES ───
["কম","kom","few / less","adjectives","adjective","আজ কম ঘুমিয়েছি। (aj kom ghumiyechhi — I slept less today.)"],
["ধরনের","dhoroner","of the kind / type of","adjectives","adjective","এই ধরনের সমস্যা সাধারণ। (ei dhoroner somosshā sādhāron — This type of problem is common.)"],
// ─── ADVERBS ───
["আরও","aro","more","adverbs","adverb","আরও সময় লাগবে। (aro shomoy lagbe — More time will be needed.)"],
["সবচেয়ে","sobcheye","most / the most","adverbs","adverb","এটি সবচেয়ে ভাল উপায়। (eti sobcheye bhal upay — This is the best way.)"],
["সেখানে","shekhane","there","adverbs","adverb","সে সেখানে আছে। (she shekhane achhe — She is there.)"],
["বেশ","besh","quite / rather / fairly","adverbs","adverb","এটি বেশ ভাল। (eti besh bhal — This is quite good.)"],
["যেখানে","jekkhāne","where / wherever","adverbs","adverb","যেখানে তুমি যাও, আমি তোমার সাথে থাকব। (jekkhāne tumi yāo, āmi tomār sāthe thākbo — Wherever you go, I will be with you.)"],
["একটু","ektu","a little","adverbs","adverb","একটু অপেক্ষা করো। (ektu opekha koro — Wait a little.)"],
// ─── GRAMMAR ───
["যেন","jeno","as if / so that","grammar","conjunction","মনে হচ্ছে যেন স্বপ্ন দেখছি। (mone hocche jeno shopno dekhchhi — It feels as if I am dreaming.)"],
["ফলে","phole","as a result","grammar","conjunction","পরিশ্রমের ফলে সে সফল হলো। (porishhromer phole she shophol holo — As a result of hard work, she succeeded.)"],
["ছাড়া","chhara","without / except","grammar","postposition","তুমি ছাড়া আমি একা। (tumi chhara ami eka — Without you, I am alone.)"],
["যেমন","jemon","as / like / for example","grammar","conjunction","যেমন কর্ম তেমন ফল। (jemon kormo temon phol — As you act, so you reap.)"],
["চেয়ে","cheye","than (comparison)","grammar","postposition","আম কাঁঠালের চেয়ে বেশি মিষ্টি। (am kathhaler cheye beshi mishti — Mango is sweeter than jackfruit.)"],
["নাকি","naki","or (question)","grammar","particle","তুমি যাবে নাকি থাকবে? (tumi jabe naki thakbe — Will you go or stay?)"],
["বিষয়ে","bishoye","about / regarding","grammar","postposition","এই বিষয়ে আমার কিছু বলার আছে। (ei bishoye amar kichhu bolar achhe — I have something to say about this matter.)"],
// ─── SOCIETY ───
["মানুষের","manusher","of the people / of people","society","noun","মানুষের অধিকার গুরুত্বপূর্ণ। (manusher adhikar gurutwopurn — People's rights are important.)"],
["দলের","daler","of the team / of the group","society","noun","দলের নেতা আমি। (daler neta ami — I am the team leader.)"],
// ─── ABSTRACT ───
["মাধ্যমে","madhdhame","through / by means of","abstract","preposition","সোশ্যাল মিডিয়ার মাধ্যমে খবর ছড়ায়। (shoshal midia'r madhdhame khabor chhoray — News spreads through social media.)"],
// ─── SOCIETY ───
["নারী","nari","woman","society","noun","নারী শিক্ষা জরুরি। (nari shikkha joruri — Women's education is important.)"],
["নির্বাচন","nirbachon","election","society","noun","নির্বাচন অনুষ্ঠিত হবে। (nirbachon anushthito hobe — The election will be held.)"],
// ─── ABSTRACT ───
["মত","mot","opinion / like","abstract","noun","আমার মত হলো এটা ঠিক না। (amar mot holo eta thik na — In my opinion, this is not right.)"],
// ─── SOCIETY ───
["শিক্ষা","shikkha","education","society","noun","শিক্ষাই জাতির মেরুদণ্ড। (shikkhai jatir meruddondo — Education is the backbone of a nation.)"],
["সরকারের","sorkarer","government's / of the government","society","noun","সরকারের নীতি খুবই গুরুত্বপূর্ণ। (sorkarer nīti khubui guruttopoorno — The government's policy is very important.)"],
// ─── ABSTRACT ───
["বিরুদ্ধে","biruddhe","against / opposed to","abstract","preposition","তিনি এই প্রস্তাবের বিরুদ্ধে। (tin ei prastaber biruddhe — He is against this proposal.)"],
// ─── SOCIETY ───
["মৃত্যু","mrittu","death","society","noun","মৃত্যু জীবনের অনিবার্য পরিণতি। (mrittu jiboner onibarro porinoti — Death is the inevitable conclusion of life.)"],
["খবর","khobor","news","society","noun","ভালো খবর আছে। (bhalo khobor achhe — There is good news.)"],
// ─── ABSTRACT ───
["কারণে","karone","because of / due to","abstract","preposition","বৃষ্টির কারণে খেলা বন্ধ হয়েছে। (brishti'r karone khela bondh hoeche — The game is cancelled due to rain.)"],
["অংশ","ongsh","part / portion / share","abstract","noun","এটি আমার অংশ। (eti amar ongsh — This is my part.)"],
["প্রকাশ","prakash","expression / manifestation / light","abstract","noun","তার আবেগের প্রকাশ স্পষ্ট। (tar abegger prakash shapst — The expression of his emotion is clear.)"],
["নামে","name","named / by the name of","abstract","preposition","তার নামে একটি স্কুল আছে। (tar name ekti shkul ache — There is a school in his name.)"],
["চেষ্টা","cheshta","effort / attempt / endeavor","abstract","noun","তার প্রচেষ্টা প্রশংসার যোগ্য। (tar procheshta prashonsar joggo — His effort is praiseworthy.)"],
["মাঝে","māzhe","middle / among / between","abstract","preposition","গাছের মাঝে একটি পাখি আছে। (gaćher māzhe ekti pākhi āche — There is a bird among the trees.)"],
["সম্পর্কে","somporke","about / concerning / regarding","abstract","preposition","এই বিষয়ে সম্পর্কে আরও জানুন। (ei bishoy somporkke āro jānun — Learn more about this matter.)"],
["তথ্য","tothyo","information / data","abstract","noun","সঠিক তথ্য দেওয়া দরকার। (shothik tothyo deowa dorkar — It is necessary to give correct information.)"],
["টি","ti","the / it (particle)","abstract","particle","বইটি খুবই ভালো। (boiti khubuī bhālo — The book is very good.)"],
["ক্ষেত্রে","kshetre","in case / in the matter / in the field","abstract","preposition","এই ক্ষেত্রে আপনার পরামর্শ প্রয়োজন। (ei kshetre āpnār porāmorsho proyojon — Your advice is needed in this matter.)"],
// ─── EXPRESSIONS ───
["ধন্যবাদ","dhonnobad","thank you","expressions","expression","সাহায্যের জন্য ধন্যবাদ। (shahajyer jonno dhonnobad — Thank you for the help.)"],
// ─── PRONOUNS ───
["ওই","oi","that","pronouns","pronoun","ওই মেয়েটি কে? (oi meye ti ke — Who is that girl?)"],
["কিভাবে","kibhabe","how","pronouns","pronoun","তুমি কিভাবে এলে? (tumi kibhabe ele — How did you come?)"],
["সেটা","setā","that / it","pronouns","pronoun","এটি একটি ভালো সিদ্ধান্ত এবং সেটা সবাই বুঝতে পারে। (eti ekti bhālo siddhānto ebong setā sobāi bujhte pāre — This is a good decision and everyone can understand that.)"],
["সবার","sbar","of everyone / everyone's","pronouns","pronoun","এটি সবার জন্য গুরুত্বপূর্ণ। (eta sbar jonno gurutpurn — This is important for everyone.)"],
["আপনাকে","apnake","you (formal)","pronouns","pronoun","আপনাকে আমরা সম্মান করি। (apnake amra somman kori — We respect you.)"],
["নিজেকে","nijeke","oneself / himself / herself","pronouns","pronoun","তিনি নিজেকে আহত করেছেন। (tin nijeke ahat korech — He has injured himself.)"],
["কোথায়","kothay","where","pronouns","pronoun","তুমি কোথায় থাকো? (tumi kothay thako — Where do you live?)"],
["তোমাকে","tomake","you / to you","pronouns","pronoun","আমি তোমাকে একটি উপহার দিতে চাই। (ami tomake ekti uphhar ditē chai — I want to give you a gift.)"],
["ঐ","oi","that / those","pronouns","pronoun","ঐ ছেলেটি আমার বন্ধু। (oi chhelēti amar bondhу — That boy is my friend.)"],
["যিনি","jini","who (honorific) / that person who","pronouns","pronoun","যিনি এখানে এসেছেন তিনি আমার শিক্ষক। (jini ekhane eschhen tini amar shikkhok — The person who came here is my teacher.)"],
["কোনও","kono'o","any / some","pronouns","pronoun","কোনও সমস্যা নেই। (kono'o somossha nei — There is no problem.)"],
["আপনাদের","apnader","your (plural/respectful)","pronouns","pronoun","আপনাদের মতামত শুনতে চাই। (apnader motamot shunte chai — I want to hear your opinion.)"],
["কিছুই","kichu-i","nothing at all","pronouns","pronoun","এটি কিছুই নয়। (eti kichu-i noy — It is nothing.)"],
["নিজেদের","nijeder","their own / themselves","pronouns","pronoun","তারা নিজেদের ভাবে চলেছে। (tara nijeder bha'be chleche — They are proceeding in their own way.)"],
["আপনারা","apnara","you all (formal)","pronouns","pronoun","আপনারা কোথা থেকে এসেছেন? (apnara kotha theke eshechen — Where have you all come from?)"],
["সবাইকে","sobai-ke","everyone (accusative)","pronouns","pronoun","সবাইকে আমন্ত্রণ করেছি। (sobai-ke amontrnn korechi — I have invited everyone.)"],
["কাউকে","kauke","anyone / to anyone","pronouns","pronoun","আমি কাউকে বলিনি। (ami kauke bolni — I didn't tell anyone.)"],
["কারো","karo","anyone's / someone's","pronouns","pronoun","এটি কারো নয়। (eti karo noy — It is not anyone's.)"],
["এদের","eder","their / these people's","pronouns","pronoun","এদের ঘর এখানে আছে। (eder ghor ekhane ache — Their house is here.)"],
["তোর","tor","your (informal)","pronouns","pronoun","এটি তোর বই। (eti tor boi — This is your book.)"],
["তুই","tui","you (very informal)","pronouns","pronoun","তুই আমার বন্ধু। (tui amar bondhu — You are my friend.)"],
["এরা","era","they","pronouns","pronoun","এরা আমার বন্ধু। (era amar bondu — They are my friends.)"],
["তাদেরকে","taderke","them (objective)","pronouns","pronoun","আমরা তাদেরকে সাহায্য করব। (amra taderke sahay korbo — We will help them.)"],
["যাদের","jader","whose / of whom","pronouns","pronoun","যাদের টাকা আছে তারা কিনতে পারে। (jader taka ache tara kinte pare — Those who have money can buy.)"],
["তোমরা","tomra","you all (informal)","pronouns","pronoun","তোমরা কি খাবে? (tomra ki khabe — What will you all eat?)"],
// ─── NUMBERS ───
["দু","du","two","numbers","number","আমার দুটি বই আছে। (amar duti boi ache — I have two books.)"],
["কোটি","koti","crore (ten million)","numbers","number","দেশের জনসংখ্যা পঞ্চাশ কোটি। (deshr jonsonkhya ponchas koti — The country's population is fifty crore.)"],
["দ্বিতীয়","dwitio","second","numbers","adjective","তিনি দ্বিতীয় স্থান পেয়েছেন। (tin dwitio sthan peyechen — He got the second place.)"],
["দুটি","duti","two","numbers","number","দোকানে দুটি নতুন পণ্য এসেছে। (dokane duti notun pōnno eschhe — Two new products have arrived at the shop.)"],
["বার","bar","time / occasion / times / instances","numbers","noun","আমরা অনেক বার এখানে এসেছি। (amra oney bar ekhane eschhi — We have come here many times.)"],
["কয়েক","koyok","a few / several","numbers","number","কয়েক জন এসেছেন। (koyok jon esechen — A few people have come.)"],
["চার","char","four","numbers","number","ঘরে চারটা চেয়ার আছে। (ghore charta cheyar achhe — There are four chairs in the room.)"],
["লাখ","lakh","hundred thousand","numbers","number","বাড়িটা দশ লাখ টাকায় বিক্রি হয়েছে। (barita dosh lakh takay bikri hoyeche — The house was sold for one million takas.)"],
["একবার","ekbar","once / one time","numbers","number","আমি একবার গিয়েছিলাম। (ami ekbar giechhhilam — I went once.)"],
["কয়েকটি","koyekti","a few / several","numbers","number","কয়েকটি বই আছে। (koyekti boi ache — There are several books.)"],
["পাঁচ","pach","five","numbers","number","আমি পাঁচটা রুটি কিনলাম। (ami pachta ruti kinlam — I bought five rotis.)"],
["শতাংশ","shotansh","percent / percentage","numbers","number","আশি শতাংশ মানুষ সম্মত। (ashi shotansh manush shomot — Eighty percent of people agree.)"],
// ─── VERBS ───
["আসে","āse","comes / happens","verbs","verb","প্রতিদিন সকালে সে আসে। (protidin sokale she ashe — He comes every morning.)"],
["থাকবে","thākbe","will be / will remain / will stay","verbs","verb","সে আগামীকাল এখানে থাকবে। (she agamikal ekhane thakbe — He will be here tomorrow.)"],
["করছেন","korchen","is doing / are doing","verbs","verb","তারা এখন কাজ করছেন। (tārā ekhon kāj korchen — They are working now.)"],
["চায়","chāy","wants / wishes / desires","verbs","verb","সে শিক্ষা চায়। (she shikshā chāy — She wants education.)"],
["তুলে","tule","raising / lifting / picking up","verbs","verb","তিনি হাত তুলে প্রশ্ন জিজ্ঞাসা করেছেন। (tini hāt tule proshn jijjnāsā korechen — He raised his hand and asked a question.)"],
["দেন","den","gives / give","verbs","verb","দয়া করে আমাকে সাহায্য দেন। (doyā kore āmāke sāhāyy den — Please help me.)"],
["ফিরে","fire","returning / coming back","verbs","verb","সে কাজ শেষ করে ফিরে এসেছে। (she kāj shesh kore fire eseche — He finished work and came back.)"],
["বলেছেন","bolechen","has said / said","verbs","verb","তিনি এটি স্পষ্টভাবে বলেছেন। (tini eti spashṭbhābe bolechen — He said this clearly.)"],
["বলেন","bolen","says / tell / speak","verbs","verb","তিনি সবসময় সত্য কথা বলেন। (tini sobsomoye sotty kothā bolen — He always tells the truth.)"],
["থাকা","thaka","to stay / to live / to exist","verbs","verb","সে ঢাকায় থাকে। (she dhakay thake — She lives in Dhaka.)"],
["যাওয়া","jaowa","to go","verbs","verb","আমি বাজারে যাচ্ছি। (ami bajare jacchhi — I am going to the market.)"],
["পারি","pari","can / am able to","verbs","verb","আমি এটা করতে পারি। (ami eta korte pari — I can do this.)"],
["যান","jan","go / depart / travel","verbs","verb","তিনি প্রতিদিন ঢাকায় যান। (tini protidin dhakay jan — He goes to Dhaka every day.)"],
["হওয়া","howa","to be / to become","verbs","verb","ডাক্তার হওয়া সহজ না। (daktar hoa shohoj na — Becoming a doctor is not easy.)"],
["করছি","korchi","am doing / are doing","verbs","verb","আমি এখন কাজ করছি। (ami ekhon kaj korchi — I am working now.)"],
["থাকতে","thakte","to stay / to remain / to keep","verbs","verb","তিনি এখানে থাকতে চান। (tin ekhane thakte chan — He wants to stay here.)"],
["শেখ","shekh","to learn / to teach","verbs","verb","তুমি বাংলা শেখ। (tumi bangla shekh — Learn Bengali.)"],
["জানতে","jante","to know / to learn","verbs","verb","আমি এটি জানতে চাই। (ami eta jante chai — I want to know this.)"],
["মারা","mara","to hit / to beat","verbs","verb","কাউকে মারা ঠিক না। (kauke mara thik na — Hitting someone is not right.)"],
["হয়নি","hoyni","has not been / did not happen","verbs","verb","এটি হয়নি কারণ সবাই বিরোধী ছিল। (eta hoyni karon soba birodhi chil — This did not happen because everyone opposed.)"],
["এসেছে","eseche","has come / have come","verbs","verb","সে আজ আমাদের বাড়িতে এসেছে। (she aj amader brite eseche — She has come to our house today.)"],
["আসছে","aschche","is coming / are coming","verbs","verb","সে আগামীকাল আসছে। (she agamikal aschche — He is coming tomorrow.)"],
["যাওয়ার","jawar","of going / going's","verbs","verb","দেশ যাওয়ার আগে বিদায় নিন। (desh jawar age biday nin — Say goodbye before going to the country.)"],
// ─── FAMILY ───
["পরিবারের","paribarer","family's / of the family","family","noun","পরিবারের সকল সদস্য উপস্থিত ছিল। (paribarer sokol shōdoshyo upōsthit chhil — All family members were present.)"],
["বিয়ে","biē","marriage / wedding","family","noun","তাদের বিয়ে হবে পরের মাসে। (tader biē hōbē pōrer mashe — Their wedding will be next month.)"],
["মহিলা","mohila","woman / female","family","noun","একজন মহিলা এসেছিলেন। (ekjon mohila esechhhilen — A woman came.)"],
["মায়ের","mayer","mother's","family","noun","মায়ের ভালোবাসা অতুলনীয়। (mayer valobasha otulniy — Mother's love is incomparable.)"],
// ─── ADJECTIVES ───
["অন্যান্য","onnānno","other / various / miscellaneous","adjectives","adjective","অন্যান্য বিষয়ে আমরা পরে আলোচনা করব। (onnānno bishōye āmrā pore āloĉnā korbo — We will discuss other matters later.)"],
["রাজনৈতিক","rājonortik","political","adjectives","adjective","রাজনৈতিক পরিস্থিতি খুবই জটিল। (rājonortik porisstiti khubuī jotil — The political situation is very complex.)"],
["উচিত","uchit","should / ought / proper","adjectives","adjective","তোমার এটি করা উচিত। (tomār eti korā uchit — You should do this.)"],
["নিশ্চিত","nischit","certain / sure / definite","adjectives","adjective","তিনি নিশ্চিত যে সে আসবে। (tin nischit je se asbe — He is certain that he will come.)"],
["ভারতীয়","bharotio","Indian","adjectives","adjective","তিনি একজন ভারতীয় নাগরিক। (tin ekjon bharotio nagrik — He is an Indian citizen.)"],
["এত","et","so much / so many / this much","adjectives","adjective","এত দিন আমরা অপেক্ষা করেছি। (et din amra opekkha korech — We have waited so long.)"],
];

const VOCAB_TOTAL_WORDS = 4399; // updated by build_vocab_packs.py

// VOCAB_DATA is mutable so lazy-loaded packs can be appended at runtime.
// Pack 0 is inlined here; packs 1-3 are fetched from vocab-pack-N.json.
let VOCAB_DATA = VOCAB_DATA_RAW.map(([lemma, roman, english, category, pos, example, senseId = '', related = []], index) => ({
  lemma,
  roman,
  english,
  category,
  pos,
  example: example || '',
  senseId: senseId || '',
  related: Array.isArray(related) ? related : [],
  freqRank: index + 1,
}));


// Category metadata
const VOCAB_CATEGORIES = {
  "pronouns":    { title:"Pronouns & Questions", icon:"👤", color:"#ce82ff" },
  "numbers":     { title:"Numbers", icon:"🔢", color:"#49c0f8" },
  "family":      { title:"Family & People", icon:"👪", color:"#ff9600" },
  "body":        { title:"Body & Health", icon:"🦴", color:"#ff6b6b" },
  "food":        { title:"Food & Drink", icon:"🍚", color:"#ffc800" },
  "animals":     { title:"Animals", icon:"🐅", color:"#58cc02" },
  "colors":      { title:"Colors", icon:"🎨", color:"#ff9600" },
  "time":        { title:"Time & Calendar", icon:"🕐", color:"#49c0f8" },
  "nature":      { title:"Nature & Weather", icon:"🌳", color:"#58cc02" },
  "home":        { title:"Home & Objects", icon:"🏠", color:"#ce82ff" },
  "places":      { title:"Places", icon:"📍", color:"#ff6b6b" },
  "verbs":       { title:"Common Verbs", icon:"🏃", color:"#49c0f8" },
  "adjectives":  { title:"Adjectives", icon:"📐", color:"#ffc800" },
  "adverbs":     { title:"Adverbs & Connectors", icon:"🔗", color:"#ce82ff" },
  "expressions": { title:"Greetings & Phrases", icon:"🗣️", color:"#58cc02" },
  "professions": { title:"Professions", icon:"💼", color:"#ff9600" },
  "transport":   { title:"Transport", icon:"🚗", color:"#49c0f8" },
  "clothing":    { title:"Clothing & Accessories", icon:"👕", color:"#ff6b6b" },
  "emotions":    { title:"Emotions & Feelings", icon:"❤️", color:"#ff6b6b" },
  "education":   { title:"Education & Work", icon:"📚", color:"#ffc800" },
  "society":     { title:"Society & Religion", icon:"🏛️", color:"#ce82ff" },
  "abstract":    { title:"Abstract & General", icon:"💡", color:"#49c0f8" },
  "grammar":     { title:"Grammar Words", icon:"📖", color:"#ff9600" },
  "health":      { title:"Health & Medicine", icon:"🏥", color:"#ff6b6b" },
  "technology":  { title:"Technology", icon:"💻", color:"#49c0f8" },
  "phrases":     { title:"Useful Phrases", icon:"💬", color:"#58cc02" },
};


export { VOCAB_DATA_RAW, VOCAB_TOTAL_WORDS, VOCAB_DATA, VOCAB_CATEGORIES };
